<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Diego Franco, Daniel Gonzalez, Angel Carrera">

<title>Proyecto</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Proyecto_files/libs/clipboard/clipboard.min.js"></script>
<script src="Proyecto_files/libs/quarto-html/quarto.js"></script>
<script src="Proyecto_files/libs/quarto-html/popper.min.js"></script>
<script src="Proyecto_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Proyecto_files/libs/quarto-html/anchor.min.js"></script>
<link href="Proyecto_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Proyecto_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Proyecto_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Proyecto_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Proyecto_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Proyecto</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Diego Franco, Daniel Gonzalez, Angel Carrera </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="defunciones-fetales-en-guatemala" class="level2">
<h2 class="anchored" data-anchor-id="defunciones-fetales-en-guatemala">Defunciones fetales en Guatemala</h2>
<section id="situacion-problematica" class="level3">
<h3 class="anchored" data-anchor-id="situacion-problematica">Situacion Problematica</h3>
<p>La falta de una atención médica adecuada durante el parto trae múltiples problemas. Por un lado, produce complicaciones que desembocan en múltiples defunciones fetales. Además, también pone en riesgo la salud y vida de la madre. Por lo tanto, el acceso a atención médica adecuada y condiciones higiénicas puede reducir el riesgo de muerte. En Guatemala fallecen anualmente cerca de 2800 fetos, por lo que un sistema de salud adecuado es imprescindible para poder mitigar el peligro de las muertes durante el parto.</p>
<p>Un estudio por (Kestler &amp; Ambrosio, 2022), mostró que la atención de una emergencia obstétrica por parte de personal capacitado, puede ayudar a reducir en un 23% el riesgo de muerte del feto. También se evidenció que la mayor cantidad de defunciones fetales se da en ámbitos no hospitalarios, con el 81%. Estos partos son atendidos por comadronas o familiares que pueden no tener la preparación necesaria. Algunos de los factores que influyen en la asistencia recibida por las madres pueden ser la edad, la escolaridad de la madre y el acceso a instalaciones adecuadas.</p>
<p>Por otra parte, existe una brecha en la cantidad de emergencias atendidas en el área urbana y rural. 83% de los partos atendidos en el área urbana son atendidos en centros adecuados de salud, mientras que en el área rural solo 55%. Desde luego, Guatemala es el departamento que más partos atiende en centros de salud, seguido por Escuintla y Santa Rosa. (MSPAS, 2017)</p>
<p>En Guatemala se puede observar que la asistencia prenatal es muy baja, lo que es realmente delicado porque la falta de acceso a servicios de salud adecuados durante un embarazo puede traer graves consecuencias tanto para la madre como para el feto, en este caso se pude observar que llega al punto de contribuir a gran cantidad de defunciones fetales.</p>
<p>Con esta situación es necesario tomar medidas para mejorar en generar los servicios de salud en el país, enfocándose en brindar una asistencia prenatal de mejor calidad para reducir cualquier riesgo relacionado con el embarazo de la madre y disminuir las defunciones fetales.</p>
</section>
<section id="problema-científico" class="level3">
<h3 class="anchored" data-anchor-id="problema-científico">Problema Científico</h3>
<p>A raiz de que existe esta situación a nivel nacional nos queremos enfocar en determinar si el factor geografico influye en la calidad de asistencia que se puede brindar, asimismo evaluar la eficiencia de las intervenciones actuales de cada region para proponer posibles soluciones de mejora que aborden las regiones que tengan una calidad de asistencia más baja.</p>
<p>Por lo mismo el <em>objetivo principal</em> de este estudio es:</p>
<ul>
<li>Analizar la relación entre la baja asistencia prenatal y la tasa de mortalidad fetal en las diferentes regiones de Guatemala.</li>
</ul>
<p>Dentro de los <em>objetivos especificos</em> se encuentra:</p>
<ul>
<li>Analizar la relacion que existe entre la educacion materna y la asistencia prenatal en Guatemala.</li>
<li>Determinar si existen patrones temporales en las defunciones fetales a nivel nacional.</li>
<li>Obtener las primeras 5 regiones que necesitan mejorar la calidad de asistencia prenatal en Guatemala.</li>
</ul>
</section>
<section id="tipo-de-cada-una-de-las-variables-de-dataset." class="level3">
<h3 class="anchored" data-anchor-id="tipo-de-cada-una-de-las-variables-de-dataset.">Tipo de cada una de las variables de dataset.</h3>
<ul>
<li>DEPREG (Departamento de registro) -&gt; Categórica nominal<br>
</li>
<li>MUPREG (Municipio de registro) -&gt; Categórica nominal<br>
</li>
<li>MESREG (Mes de registro) -&gt; Categórica nominal<br>
</li>
<li>AÑOREG (Año de registro) -&gt; Categórica nominal<br>
</li>
<li>DEPOCU (Departamento de ocurrencia) -&gt; Categórica nominal<br>
</li>
<li>MUPOCU (Municipio de ocurrencia) -&gt; Categórica nominal<br>
</li>
<li>SEXO (de la defunción fetal) -&gt; Categórica nominal<br>
</li>
<li>DIAOCU (Día de ocurrencia) -&gt; Categórica nominal<br>
</li>
<li>MESOCU (Mes de ocurrencia) -&gt; Categórica nominal<br>
</li>
<li>TIPAR (Tipo de parto) -&gt; Categórica nominal<br>
</li>
<li>CLAPAR (Clase de parto) -&gt; Categórica nominal<br>
</li>
<li>VIAPAR (Via del parto) -&gt; Categórica nominal<br>
</li>
<li>SEMGES (Semanas de gestación) -&gt; Cuantitativa discreta<br>
</li>
<li>EDADM (Edad de la madre) -&gt; Cuantitativa discreta<br>
</li>
<li>DEPREM (Departamento de residencia de la madre) -&gt; Categórica nominal<br>
</li>
<li>MUPREM (Municipio de residencia de la madre) -&gt; Categórica nominal<br>
</li>
<li>ESCIVM (Estado civil de la madre) -&gt; Categórica nominal<br>
</li>
<li>NACIOM (Nacionalidad de la madre) -&gt; Categórica nominal<br>
</li>
<li>ESCOLAM (Escolaridad de la madre) -&gt; Categórica nominal<br>
</li>
<li>CAUDEF (Causa de defunción) -&gt; Categórica nominal<br>
</li>
<li>ASISREC (Asistencia recibida) -&gt; Categórica nominal<br>
</li>
<li>SITIOOCU (Sitio de ocurrencia) -&gt; Categórica nominal<br>
</li>
<li>TOHITE (Total de hijos tenidos) -&gt; Cuantitativa discreta<br>
</li>
<li>TOHINM (Total de hijos nacidos muertos) -&gt; Cuantitativa discreta<br>
</li>
<li>TOHIVI (Total de hijos vivos) -&gt; Cuantitativa discreta</li>
</ul>
</section>
<section id="análsis-de-na-y-limpieza" class="level3">
<h3 class="anchored" data-anchor-id="análsis-de-na-y-limpieza">1. Análsis de NA y limpieza</h3>
<p>Los datos tienen un encoding en el que se pone un número (como 99 o 999) para indicar que no se tiene información. Por lo tanto es necesario reemplazar estos números por NA.</p>
<div class="cell">

</div>
<p>Además, también se tienen muchas variables con valores numéricos pero que son cualitativas. Por lo tanto, se conviertieron en factores.</p>
<div class="cell">

</div>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>  DEPREG   MUPREG   MESREG   AÑOREG   DEPOCU   MUPOCU     SEXO   DIAOCU 
       0        0        0        0        0        0      173        0 
  MESOCU    TIPAR   CLAPAR   VIAPAR   SEMGES    EDADM   DEPREM   MUPREM 
       0        0        0        0     4163     1153       87     1562 
  ESCIVM   NACIOM  ESCOLAM   CAUDEF  ASISREC SITIOOCU   TOHITE   TOHINM 
     773        0     3231        0        0     3043    16252    10796 
  TOHIVI 
   13149 </code></pre>
</div>
</div>
<p>Es posible observar que se tienen valores faltantes en la cantidad de hijos tenidos, de hijos fallecidos y de hijos vivos. Además, también se tienen en el sexo de la defunción, la semana de gestación, la edad de la madre, el departamenteo y municipio de residencia de la madre, la escolaridad de la madre y el estado civil de la madre.</p>
<p>Los datos faltantes no se eliminaron acá, si no que al momento de hacer clustering se obtuvieron las variables cuantitativas y a esas se les quitaron los NA.</p>
</section>
<section id="resúmen-del-conjunto-de-datos." class="level3">
<h3 class="anchored" data-anchor-id="resúmen-del-conjunto-de-datos.">2. Resúmen del conjunto de datos.</h3>
<p>El conjunto de datos está compuesto por 36065 filas y 25 columnas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(datos)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     DEPREG          MUPREG          MESREG          AÑOREG     
 1      : 8854   101    : 7668   1      : 3302   2013   : 3340  
 16     : 5144   1601   : 2751   7      : 3116   2010   : 3332  
 14     : 2695   901    : 1449   10     : 3105   2011   : 3273  
 9      : 2560   701    : 1436   8      : 3092   2014   : 3229  
 4      : 2014   401    : 1114   5      : 3079   2016   : 3163  
 7      : 1980   1615   :  876   11     : 3065   2012   : 3137  
 (Other):12818   (Other):20771   (Other):17306   (Other):16591  
     DEPOCU          MUPOCU        SEXO           DIAOCU          MESOCU     
 1      : 8849   101    : 7447   1   :18965   5      : 1270   1      : 3195  
 16     : 5139   1601   : 2875   2   :16927   4      : 1250   8      : 3080  
 14     : 2707   901    : 1570   NA's:  173   6      : 1242   10     : 3078  
 9      : 2601   701    : 1513                14     : 1231   7      : 3069  
 4      : 1989   401    : 1183                18     : 1227   5      : 3050  
 7      : 1945   1301   :  912                28     : 1225   9      : 3048  
 (Other):12835   (Other):20565                (Other):28620   (Other):17545  
 TIPAR     CLAPAR    VIAPAR        SEMGES          EDADM           DEPREM     
 1:34870   1:27739   1:27801   Min.   : 1.00   Min.   :10.00   1      : 6808  
 2: 1167   2: 8326   2: 8264   1st Qu.:31.00   1st Qu.:22.00   16     : 4866  
 3:   28                       Median :36.00   Median :27.00   14     : 2878  
                               Mean   :34.41   Mean   :27.67   9      : 2193  
                               3rd Qu.:39.00   3rd Qu.:33.00   4      : 2191  
                               Max.   :44.00   Max.   :57.00   (Other):17042  
                               NA's   :4163    NA's   :1153    NA's   :   87  
     MUPREM       ESCIVM          NACIOM      ESCOLAM          CAUDEF     
 101    : 2341   1   :19703   320    :35025   1   :12544   P95X   :16505  
 1406   : 1108   2   :15470   9999   :  790   2   :11794   P209   :11695  
 1609   :  978   3   :  119   222    :   81   3   : 3633   P073   :  668  
 1601   :  843   NA's:  773   340    :   47   4   : 4336   Q897   :  599  
 108    :  831                723    :   47   5   :  524   Q899   :  599  
 (Other):28402                720    :   35   6   :    3   P025   :  576  
 NA's   : 1562                (Other):   40   NA's: 3231   (Other): 5423  
 ASISREC      SITIOOCU         TOHITE           TOHINM          TOHIVI      
 1:26390   1      :19910   Min.   : 1.000   Min.   : 1.00   Min.   : 0.000  
 2:  270   6      : 8121   1st Qu.: 2.000   1st Qu.: 1.00   1st Qu.: 1.000  
 3: 5818   2      : 2141   Median : 3.000   Median : 1.00   Median : 2.000  
 4:  243   4      : 1711   Mean   : 4.063   Mean   : 1.27   Mean   : 2.602  
 5: 3344   3      : 1006   3rd Qu.: 5.000   3rd Qu.: 1.00   3rd Qu.: 4.000  
           (Other):  133   Max.   :32.000   Max.   :30.00   Max.   :16.000  
           NA's   : 3043   NA's   :16252    NA's   :10796   NA's   :13149   </code></pre>
</div>
</div>
<ul>
<li>Es posible observar que la media de semanas de gestación está en 36. Un 75% de las defunciones se dieron abajo de las 44 semanas.</li>
<li>La media de la edad de las madres es de 27 años. Un 75% de las madres está por debajo de los 33 años. La madre de mayor edad tiene 57 años.</li>
<li>La media de hijos tenidos es de 4. El 75% de las madres tienen 5 hijos o menos. Existe una madre con 32 hijos tenidos. La media de hijos fallecidos es de 1.27. Un 75% de las madres solo han tenido 1 hijo fallecido. Existe una madre que tiene 30 hijos fallecidos.</li>
<li>El 75% de las madres tienen 4 o menos hijos vivos. Existe una madre que tiene 16 hijos vivos.</li>
</ul>
</section>
<section id="analisis-de-las-variables" class="level3">
<h3 class="anchored" data-anchor-id="analisis-de-las-variables">3. Analisis de las variables</h3>
<div class="cell">

</div>
</section>
<section id="análisis-de-normalidad-varibales-cuantitativas" class="level3">
<h3 class="anchored" data-anchor-id="análisis-de-normalidad-varibales-cuantitativas">3.2 Análisis de normalidad varibales cuantitativas</h3>
</section>
<section id="prueba-de-normalidad-para-semges." class="level3">
<h3 class="anchored" data-anchor-id="prueba-de-normalidad-para-semges.">Prueba de normalidad para <strong>SEMGES</strong>.</h3>
<p>Inicialmente se muestra un histograma de la distribución de EDADM.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se puede observar del histograma que hay datos muy atípicos en el extremo derecho. Es muy probable que la distribución no sea normal. Es posible observar que hay una fuerte frecuencia en el extremo derecho, como se mencionó.</p>
<p>A continuación se realizó un QQplot para observar la distribución de los valores de SEMGES.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se puede observar del gráfico que la cola izquierda se aleja de la línea teórica y la cola derecha está mucho más alejada. Por lo tanto, la distribución de los datos no es normal.</p>
<p>A continuación se hizo un test de normalidad con Lilliefors.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Lilliefors (Kolmogorov-Smirnov) normality test

data:  semana_ges$SEMGES
D = 0.181, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Es posible observar que el valor p es muy pequeño, mucho menor que el nivel de significancia de 0.05. Por lo tanto, se puede afirmar que la distribución de los datos no es normal.</p>
</section>
<section id="prueba-de-normalidad-para-edadm." class="level3">
<h3 class="anchored" data-anchor-id="prueba-de-normalidad-para-edadm.">Prueba de normalidad para <strong>EDADM</strong>.</h3>
<p>Inicialmente se muestra un histograma de la distribución de EDADM.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Es posible observar del histograma que la distribución de los datos esta sesgada hacia la derecha. Es muy posible que no sea normal.</p>
<p>A continuación se realizó un QQplot para observar la distribución de los valores de EDADM.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Al observar el gráfico se puede observar que los extremos están bastante alejados de la línea teórica, por lo que es muy probable que no se tenga una distribución normal.</p>
<p>Finalmente se hizo un test de normalidad con Lilliefors.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Lilliefors (Kolmogorov-Smirnov) normality test

data:  edad_madre$EDADM
D = 0.080576, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Se puede observar que el valor p es mucho menor al nivel de significancia, que es de 0.05, por lo que se puede afirmar que la distribución no sigue una distribución normal.</p>
</section>
<section id="prueba-de-normalidad-para-tohite." class="level3">
<h3 class="anchored" data-anchor-id="prueba-de-normalidad-para-tohite.">Prueba de normalidad para <strong>TOHITE</strong>.</h3>
<p>Inicialmente se muestra un histograma de la distribución de TOHITE.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se observar del histograma que hay un fuerte sesgo hacia la izquierda. La forma de la distribución no parece normal.</p>
<p>A continuación se realizó un QQplot para observar la distribución de los valores de TOHITE.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se puede observar que la gráfica tiene una forma de gradas. La distribución está bastante alejada de la línea teórica. Es muy probable que no sea normal.</p>
<p>Finalmente se realizó un test de normalidad con Lilliefors.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Lilliefors (Kolmogorov-Smirnov) normality test

data:  hijos_tenidos$TOHITE
D = 0.20125, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Es posible observar que el valor de p es mucho más bajo al nivel de significancia. Se puede afirmar que la distribución no sigue una forma normal.</p>
</section>
<section id="prueba-de-normalidad-para-tohinm." class="level3">
<h3 class="anchored" data-anchor-id="prueba-de-normalidad-para-tohinm.">Prueba de normalidad para <strong>TOHINM</strong>.</h3>
<p>Inicialmente se muestra un histograma de la distribución de TOHINM.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se puede observar que la mayor cantidad de datos se encuentra en el extemo izquierdo. La distribución no tiene forma normal.</p>
<p>A continuación se realizó un QQplot para observar la distribución de los valores de TOHINM.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-18-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>El extremo derecho se aleja bastante de la línea teórica. Es muy probable que no se tenga una distribución normal de los datos.</p>
<p>Finalmente se hizo un test de normalidad con Lilliefors.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Lilliefors (Kolmogorov-Smirnov) normality test

data:  hijos_muertos$TOHINM
D = 0.46948, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Se puede observar que el valor p es mucho menor que el nivel de significancia, de 0.05, por lo que se rechaza la hipótesis de que la distribución es normal.</p>
</section>
<section id="prueba-de-normalidad-para-tohivi." class="level3">
<h3 class="anchored" data-anchor-id="prueba-de-normalidad-para-tohivi.">Prueba de normalidad para <strong>TOHIVI</strong>.</h3>
<p>Inicialmente se muestra un histograma de la distribución de TOHIVI.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se puede observar que se tiene un sesgo a la izquierda. La distribución no tiene formal normal.</p>
<p>A continuación se realizó un QQplot para observar la distribución de los valores de TOHIVI.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-21-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se observa que la distribución tiene una forma de gradas y se aleja bastante de la línea teórica. Es muy probable que no sea normal.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    Lilliefors (Kolmogorov-Smirnov) normality test

data:  hijos_vivos$TOHIVI
D = 0.23624, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>El valor de p es mucho menor que el nivel de significancia, por lo que se rechaza la hipótesis de que se tiene una distribución normal.</p>
</section>
<section id="análisis-de-distribución-de-variables-cuantitativas" class="level3">
<h3 class="anchored" data-anchor-id="análisis-de-distribución-de-variables-cuantitativas">3.3 Análisis de distribución de variables cuantitativas</h3>
<section id="análisis-para-semana-de-gestación" class="level4">
<h4 class="anchored" data-anchor-id="análisis-para-semana-de-gestación">Análisis para semana de gestación</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Es posible observar que un 50% de los datos están por debajo de aproximadamente la semana 37. Se tienen muchos datos atípicos en el extremo inferior. Las muertes fetales tempranas ocurren entre las 20 y 27 semanas, mientras que las tardías de 28 a 36 semanas. De esta forma, la mayoría de defunciones están en el rango de las 20 a las 40 semanas, sin embargo, en el dataset se tienen defunciones por debajo de las 20 semanas, que son los múltiples datos atípicos que se pueden observar.</p>
</section>
<section id="análisis-para-edad-de-la-madre" class="level4">
<h4 class="anchored" data-anchor-id="análisis-para-edad-de-la-madre">Análisis para edad de la madre</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Es posible observar que existen datos atípicos en el extremo superior, luego de los 50 años. La edad mínima es de 10 años. Un 50% de los datos se encuentran por debajo de aproximadamente los 27 o 28 años. Se puede observar que a partir del tercer cuartil hay más dispersión. La edad fértil de una mujer está entre los 19 y 30 años, y esta va disminuyendo hasta aproximadamente los 50 años. La mayoría de madres se encuentran entre este rango de años, pero existen datos atípicos que están arriba de los 50 años. Algo importante a resaltar es que existen madres de 10 años que se encuentran en el rango normal.</p>
</section>
<section id="análisis-para-total-de-hijos-tenidos" class="level4">
<h4 class="anchored" data-anchor-id="análisis-para-total-de-hijos-tenidos">Análisis para total de hijos tenidos</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Es posible observar que el 50% de los datos se enceuntran por debajo de los 3 hijos aproximadamente. Se puede observar una gran cantidad de datos atípicos. La menor cantidad de hijos tenidos es 1. Hay bastante dispersión después del tercer cuartil. Existe un registro que tiene 32 hijos tenidos, el valor más atípico. Además, el promedio de hijos tenidos en Guatemala es de aproximadamente 6. Los datos atípicos representan mujeres que han tenido muchos hijos, como el dato de 32 que se menciona.</p>
</section>
<section id="análisis-para-total-de-hijos-fallecidos" class="level4">
<h4 class="anchored" data-anchor-id="análisis-para-total-de-hijos-fallecidos">Análisis para total de hijos fallecidos</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-26-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se puede observar que hay una gran cantidad de datos atípicos en esta distribución. La mayoría de datos tienen 1 hijo fallecido, que muy probablemnte sea el que se registró en el dataset. Muchas madres han tenido más de 1 hijo fallecido que son los datos atípicos, hasta un dato extremo de 30 hijos fallecidos. Esta persona puede tener una condición médica que no le permite formar los hijos correctamente.</p>
</section>
<section id="análisis-para-total-de-hijos-vivos" class="level4">
<h4 class="anchored" data-anchor-id="análisis-para-total-de-hijos-vivos">Análisis para total de hijos vivos</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se puede observar que el 50% de los datos están por debajo de aproximadamente 2 hijos. Se tienen muchos datos atípicos y hay bastante dispersión en la distribución. El valor menor de hijos vivos es de 0 y hay personas que tienen más de 15 hijos vivos.</p>
</section>
</section>
<section id="análisis-de-frecuencia-varibales-cualitativas" class="level3">
<h3 class="anchored" data-anchor-id="análisis-de-frecuencia-varibales-cualitativas">3.4 Análisis de frecuencia varibales cualitativas</h3>
<p>A continuación se muestra la frecuencia de <strong>DEPREG</strong> el departamento de registro.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16 
8854  274  896 2014 1451  516 1980 1890 2560 1048  540 1395 1498 2695  905 5144 
  17   18   19   20   21   22 
 724  402  116  205  487  471 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que la mayor cantidad de abortos se registran en el departamento de Guatemala seguido de Alta Verapaz como el segundo más alto. Esto puede indicar que la mayoría de personas reciben asistencia en el departamento de Guatemala, independientemente de donde vivan.</p>
<p>A continuación se muestra la frecuencia de <strong>MUPREG</strong> el municipio de registro.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
 101  102  103  104  105  106  107  108  109  110  111  112  113  114  115  116 
7668    5   75    5   30   28   10   28   28  112   99   52   17  492   99   75 
 117  201  202  203  204  205  206  207  208  301  302  303  304  305  306  307 
  31  161    6   31    4    2   13   51    6  689   20    3   54   15   26    3 
 308  309  310  311  312  313  314  315  316  401  402  403  404  405  406  407 
   8    7    4   19   18    8   16    3    3 1114  118   99   80  136  233   57 
 408  409  410  411  412  413  414  415  416  501  502  503  504  505  506  507 
  11   26   18   32   33   25   14   14    4  503   83   12   45   81  509   59 
 508  509  510  511  512  513  514  601  602  603  604  605  606  607  608  609 
   8   73    8   25   15   19   11  375   24    4    4   11    6   11   24    7 
 610  611  612  613  614  701  702  703  704  705  706  707  708  709  710  711 
   7   11    1   18   13 1436    9    4   19  114   45   17   32   18   20    2 
 712  713  714  715  716  717  718  719  801  802  803  804  805  806  807  808 
  48   46   24   17    3   29   17   80  717   80  213   26  548  205   62   39 
 901  902  903  904  905  906  907  908  909  910  911  912  913  914  915  916 
1449   25   35   17    9  101   58   20  222    5   48   38   10   68   48   10 
 917  918  919  920  921  922  923  924 1001 1002 1003 1004 1005 1006 1007 1008 
  55    4   22  203   11    7   21   74  568   38   17   17    7   12    6   19 
1009 1010 1011 1012 1013 1014 1015 1016 1017 1018 1019 1020 1021 1101 1102 1103 
   4   70   19    1  149   31   19    9   14    5    4   20   19  381   12    4 
1104 1105 1106 1107 1108 1109 1201 1202 1203 1204 1205 1206 1207 1208 1209 1210 
   8   16   47   28   18   26  619   86   23  122   91    1    5    6    3   32 
1211 1212 1213 1214 1215 1216 1217 1218 1219 1220 1221 1222 1223 1224 1225 1226 
  11    4   24   14  157   12   11    7    6   19   18   14    5    4   33   10 
1227 1228 1229 1230 1301 1302 1303 1304 1305 1306 1307 1308 1309 1310 1311 1312 
  11    9   31    7  805   13    6    2    2   80    7    3    3   95   39    6 
1313 1314 1315 1316 1317 1319 1320 1321 1322 1323 1324 1325 1326 1327 1328 1329 
  18    8   25   93   46    8    7    5    2   11    1   95   19   63   18    5 
1330 1331 1332 1401 1402 1403 1404 1405 1406 1407 1408 1409 1410 1411 1412 1413 
   6    2    5  493  206   33  190   20  810   11   11   57   24   33   11  107 
1414 1415 1416 1417 1418 1419 1420 1421 1501 1502 1503 1504 1505 1506 1507 1508 
  47   98   25   28   16    1  473    1  548   54   51  167   13   17   13   42 
1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1611 1612 1613 1614 1615 1616 
2751   64  108   53   48   49   15   50  293   89   30   91  263   34  876  232 
1617 1701 1702 1703 1704 1705 1706 1707 1708 1709 1710 1711 1712 1713 1714 1801 
  98   28    8  120   19   44   13   12   22   20  224   49  124   32    9  289 
1802 1803 1804 1805 1901 1902 1903 1904 1905 1906 1907 1908 1909 2001 2002 2003 
  33   14   51   15   72    2    5   12    7    3    3    3    9  120    2    1 
2004 2005 2006 2007 2009 2010 2011 2101 2102 2103 2104 2105 2106 2107 2201 2202 
   4   28    6   24    4   13    3  321   28    3    1   62    6   66  289    5 
2203 2204 2205 2206 2207 2209 2210 2211 2212 2213 2214 2215 2216 2217 
   8    5   13    8    1   10    3   25   18   53   18    4    2    9 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que la mayor cantidad de abortos se registran en el municipio de Guatemala. Esto indica que en el departamento de Guatemala, es en la capital donde más se producen las defunciones fetales.</p>
<p>A continuación se muestra la frecuencia de <strong>MESREG</strong> el mes de registro.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4    5    6    7    8    9   10   11   12 
3302 2899 2869 2853 3079 2844 3116 3092 3005 3105 3065 2836 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que los meses de registro se encuentran balanceados entre si, aunque el mes con mayor registros es enero.</p>
<p>A continuación se muestra la frecuencia de <strong>AÑOREG</strong> el año de registro.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
2010 2011 2012 2013 2014 2015 2016 2017 2018 2019 2020 2021 2022 
3332 3273 3137 3340 3229 3123 3163 3033 2862 2669 2278 2534   92 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-31-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que los años de registro se encuentran bastante balanceados entre si, aunque el año con mayor registros es 2013. Se observa una tendencia a una menor cantidad de defunciones mientras pasan los años.</p>
<p>A continuación se muestra la frecuencia de <strong>DEPOCU</strong> el departamento de ocurrencia.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16 
8849  262  939 1989 1469  511 1945 1866 2601 1072  541 1357 1502 2707  902 5139 
  17   18   19   20   21   22 
 725  399  128  208  492  462 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-32-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que la mayor cantidad de abortos son ocurridos en el departamento de Guatemala seguido de Alta Verapaz como el segundo más alto.</p>
<p>A continuación se muestra la frecuencia de <strong>MUPOCU</strong> el municipio de ocurrencia.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
 101  102  103  104  105  106  107  108  109  110  111  112  113  114  115  116 
7447   17   78    3   28   17   12  166   32  117  100   40   18  589   81   59 
 117  201  202  203  204  206  207  208  301  302  304  305  306  308  309  310 
  45  183    1   21    2    5   45    5  823    9   37   10   29    1    2    1 
 311  312  313  314  315  401  402  403  404  405  406  407  408  409  410  411 
   8   10    3    4    2 1183  101   83   72  128  257   47    4   19   11   26 
 412  413  414  415  416  501  502  503  504  505  506  507  508  509  510  511 
  29   16    3    8    2  774   68    3    6   16  521   21    5   16    2   12 
 512  513  514  601  602  603  604  605  607  608  609  610  611  613  614  701 
   6   14    5  407   28    1    3    4    6   28    2    6    2   15    9 1513 
 702  703  704  705  706  707  708  709  710  711  712  713  714  715  716  717 
   7    3   13   90   26   15   28   12   12    2   41   40   23   13    2   21 
 718  719  801  802  803  804  805  806  807  808  901  902  903  904  905  906 
  14   70  870   69  174   16  476  179   52   30 1570   10   20    5    5  105 
 907  908  909  910  911  912  913  914  915  916  917  918  919  920  921  922 
  52   14  230    7   41   27    7   62   38    4   36    4   14  269    4    1 
 923  924 1001 1002 1003 1004 1005 1006 1008 1009 1010 1011 1013 1014 1015 1016 
  15   61  767   25    5    9    6    5    7    1   47   13  130   19    6    5 
1017 1018 1019 1020 1021 1101 1102 1104 1105 1106 1107 1108 1109 1201 1202 1203 
   4    1    1   11   10  487    6    1    2   24   10    2    9  694  121   19 
1204 1205 1206 1207 1208 1209 1210 1211 1212 1213 1214 1215 1216 1217 1218 1219 
  98   74    1    1    4    1   25    5    2   20    6  180    4    5    5    2 
1220 1221 1222 1223 1224 1225 1226 1227 1228 1229 1230 1301 1302 1304 1305 1306 
  10    7    4    6    1   22    8    4    6   19    3  912    3    1    1  118 
1307 1308 1309 1310 1311 1312 1313 1314 1315 1316 1317 1319 1320 1321 1323 1325 
   6   15    2   83   14    3   17    6   15   82   44    2    4    3    9   82 
1326 1327 1328 1329 1330 1331 1401 1402 1403 1404 1405 1406 1407 1408 1409 1410 
  18   39   15    4    3    1  630  176   23  177    8  765   12    3   53   13 
1411 1412 1413 1414 1415 1416 1417 1418 1419 1420 1501 1502 1503 1504 1505 1506 
  14   22  143   42   99   16   21   13    1  476  606   46   28  147   11   14 
1507 1508 1601 1602 1603 1604 1605 1606 1607 1608 1609 1610 1611 1612 1613 1614 
  13   37 2875   49  104   44   45   47   15   43  234   82   30   89  243   32 
1615 1616 1617 1701 1702 1703 1704 1705 1706 1707 1708 1709 1710 1711 1712 1713 
 881  234   92   30    7  177    6   12    2    5    4    4  262   49  156    9 
1714 1801 1802 1803 1804 1805 1901 1903 1904 1906 1909 2001 2004 2005 2006 2007 
   2  330   16    5   44    4  119    1    3    1    4  141    1   24    5   24 
2009 2010 2011 2101 2102 2105 2106 2107 2201 2203 2204 2205 2206 2207 2209 2210 
   1   11    1  431    9   26    1   25  342    1    2   11    4    1    6    3 
2211 2212 2213 2214 2215 
  18   17   44   10    3 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-33-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que la mayor cantidad de abortos son ocurridos en el municipio de Guatemala</p>
<p>A continuación se muestra la frecuencia de <strong>SEXO</strong> de la defuncion fetal.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2 
18965 16927 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-34-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que el sexo de la defuncion fetal mayormente son masculinos. Sin embargo, están bastante balanceados.</p>
<p>A continuación se muestra la frecuencia de <strong>DIAOCU</strong> el dia de ocurrencia.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4    5    6    7    8    9   10   11   12   13   14   15   16 
1117 1160 1176 1250 1270 1242 1217 1166 1200 1200 1182 1176 1180 1231 1196 1151 
  17   18   19   20   21   22   23   24   25   26   27   28   29   30   31 
1203 1227 1174 1200 1149 1160 1112 1216 1177 1170 1150 1225 1105 1060  623 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-35-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que los dias de ocurrencia estan bastante balanceados.</p>
<p>A continuación se muestra la frecuencia de <strong>MESOCU</strong> el mes de ocurrencia.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3    4    5    6    7    8    9   10   11   12 
3195 2782 2940 2905 3050 2939 3069 3080 3048 3078 3035 2944 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-36-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que al igual que con los dias los meses estan bastante balanceados pero si se puede observar que existe una mayor catidad en el mes de enero.</p>
<p>A continuación se muestra la frecuencia de <strong>TIPAR</strong> el tipo de parto.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2     3 
34870  1167    28 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-37-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que la mayoria de los partos fueron de tipo simple.</p>
<p>A continuación se muestra la frecuencia de <strong>CLAPAR</strong> el clase de parto.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2 
27739  8326 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-38-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que la mayoria de los partos fueron de clase eutocio.</p>
<p>A continuación se muestra la frecuencia de <strong>VIAPAR</strong> la via del parto.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2 
27801  8264 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-39-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que la mayoria de los partos fueron por via vaginal.</p>
<p>A continuación se muestra la frecuencia de <strong>DEPREM</strong> el departamento de residencia de la madre.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2 
18157 16214 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-40-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que la mayoria de las madres son residentes del departamento de Guatemala.</p>
<p>A continuación se muestra la frecuencia de <strong>MUPREM</strong> el municipio de residencia de la madre.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2 
18157 16214 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-41-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que la mayoria de las madres son residentes del municipio de Guatemala.</p>
<p>A continuación se muestra la frecuencia de <strong>ESCIVM</strong> el estado civil de la madre.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2 
18562 16598 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-42-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que la mayoria de las madres eran solteras.</p>
<p>A continuación se muestra la frecuencia de <strong>NACIOM</strong> la nacionalidad de la madre.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2 
18555 16583 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-43-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que casi todas las madres tienen una nacionalidad guatemalteca, aunque se muestran variedad de nacionalidades.</p>
<p>A continuación se muestra la frecuencia de <strong>ESCOLAM</strong> la escolaridad de la madre.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2     3     4     5     6 
12544 11794  3633  4336   524     3 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-44-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica indica que la gran mayoria de las madres no recibieron ningun tipo de estudios, y que el segundo grupo de madres solo llego a estudios primarios.</p>
<p>A continuación se muestra la frecuencia de <strong>CAUDEF</strong> la causa de la defuncion.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
       B24X  P000  P001  P002  P003  P004  P005  P007  P008  P009  P010  P011 
    1     2   465    47    14     5     6    30     2    47    41    20    88 
 P012  P013  P014  P015  P016  P017  P018  P019  P020  P021  P022  P023  P024 
  322    86     2    27     1   242    63    24    72   499   308     6   215 
 P025  P026  P027  P028  P029  P030  P031  P034  P035  P036  P038  P039  P043 
  576    36   107     1     2     6   137     3    24    18   189     6     2 
 P050  P051  P052  P059  P070  P072  P073  P080  P081  P082  P100  P103  P109 
    7    10     8    25    59    61   668    13     5     3     1     4     1 
 P112  P119  P130  P131  P138  P150  P158  P159  P200  P201  P209  P210  P219 
    1     1     3     5     1     1    48     7     5     2 11695     1     5 
 P220  P228  P229  P239  P240  P241  P249  P250  P251  P269  P280  P285  P288 
   76     1     5     6   202     4     3     1     4     2     6    11     1 
 P290  P291  P292  P293  P351  P369  P371  P392  P509  P518  P523  P524  P525 
    2     4    13     1     1    36     1     3     1     1     2     5     2 
 P528  P529  P546  P548  P550  P558  P569  P60X  P614  P700  P701  P702  P704 
    1     1     1     1     9     1     1     1     3     5     7    40     1 
 P708  P709  P721  P740  P741  P77X  P788  P819  P832  P835  P916  P941  P95X 
   12     6     1     1     5     2     1     3    77     2     1     1 16505 
 P964  P968  P969  Q000  Q001  Q010  Q012  Q019  Q02X  Q031  Q039  Q042  Q043 
  530    11     5   514     2     1     1    10     9    14    55     4    22 
 Q048  Q049  Q059  Q079  Q204  Q213  Q218  Q240  Q248  Q249  Q278  Q336  Q359 
    2     7    21     5     1     1     1     1     2    43     1     7     1 
 Q369  Q379  Q390  Q410  Q423  Q433  Q529  Q564  Q602  Q606  Q611  Q614  Q639 
    1     1     1     9     1     1     1     1     2    27     1     1     2 
 Q678  Q688  Q742  Q753  Q758  Q759  Q764  Q769  Q774  Q790  Q792  Q793  Q795 
    1     1     1     2     2    10     1     1     2     1     2    21     1 
 Q860  Q868  Q870  Q871  Q872  Q892  Q897  Q898  Q899  Q909  Q911  Q913  Q917 
    1     1     1     1     1     1   599     2   599    19     2     1     1 
 Q999  W499 
    4     1 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-45-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La gráfica muestra que la mayoria de las causas de defuncion son no especificadas o por Hipoxia intrauterina, no especificada.</p>
<p>A continuación se muestra la frecuencia de <strong>ASISREC</strong> la asistencia recibida.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2     3     4     5 
26390   270  5818   243  3344 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-46-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Al observar el grafico podemos observar que la mayoria de los abortos recibieron asistencia medica.</p>
<p>A continuación se muestra la frecuencia de <strong>SITIOOCU</strong> sitio de ocurrencia.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>
    1     2     3     4     5     6     7     8 
19910  2141  1006  1711    53  8121    18    62 </code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-47-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Al observar el grafico podemos observar que la mayoria de los abortos ocurrieron en un Hospital publico.</p>
</section>
<section id="matriz-de-correlación-entre-variables" class="level3">
<h3 class="anchored" data-anchor-id="matriz-de-correlación-entre-variables">3.4 Matriz de correlación entre variables</h3>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-48-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Es posible observar que existe una correlación entre la cantidad de hijos tenidos y la edad de la madre. Esto quiere decir que mientras más edad tiene una madre, más hijos ha tenido. Por otra parte, se tiene una leve correlación entre la cantidad de hijos fallecidos con la cantidad de hijos tenidos. La cantidad de hijos vivos tiene una muy fuerte correlación con la cantidad de hijos vivos. La cantidad de hijos vivos también tiene correlación con la edad de la madre.</p>
</section>
<section id="preguntas-de-investigacion" class="level3">
<h3 class="anchored" data-anchor-id="preguntas-de-investigacion">4. Preguntas de investigacion</h3>
<section id="cual-es-la-edad-promedio-de-las-madres-que-abortan" class="level4">
<h4 class="anchored" data-anchor-id="cual-es-la-edad-promedio-de-las-madres-que-abortan">4.1. ¿Cual es la edad promedio de las madres que abortan?</h4>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] 27.67369</code></pre>
</div>
</div>
<p>La edad promedio de las madres que abortan es de 27.</p>
</section>
<section id="existe-algún-patrón-temporal-en-las-defunciones-fetales" class="level4">
<h4 class="anchored" data-anchor-id="existe-algún-patrón-temporal-en-las-defunciones-fetales">4.2. ¿Existe algún patrón temporal en las defunciones fetales?</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-50-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-50-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Al observar la serie de tiempo se puede observar que hay una tendencia en la reducción de la cantidad de defunciones fetales a lo largo de los años. Un factor importante por notar es que existe una estacionalidad marcada en las defunciones fetales, se puede visualizar un ciclo que se repite aproximadamente cada año y medio en la cantidad de estas.</p>
</section>
<section id="existe-una-relación-entre-el-departamento-de-registro-y-la-atención-médica-recibida" class="level4">
<h4 class="anchored" data-anchor-id="existe-una-relación-entre-el-departamento-de-registro-y-la-atención-médica-recibida">4.3 ¿Existe una relación entre el departamento de registro y la atención médica recibida?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a>tabla_contingencia <span class="ot">&lt;-</span> <span class="fu">table</span>(datos<span class="sc">$</span>DEPREG, datos<span class="sc">$</span>ASISREC)</span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>tabla_contingencia</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>    
        1    2    3    4    5
  1  7769   34  198    6  847
  2   217    2   20    0   35
  3   802    4   52    2   36
  4  1314    6  567    6  121
  5  1252    5   86    5  103
  6   445    5   32    2   32
  7  1248   11  507   21  193
  8   860    5  843   18  164
  9  1678    5  472   22  383
  10  747    5  261    1   34
  11  450    0   46    1   43
  12  997    2  180   17  199
  13 1097   21  260    3  117
  14 1268   11 1198    8  210
  15  612   18  191    7   77
  16 3599  119  756  109  561
  17  611    3   48    3   59
  18  366    1    8    3   24
  19  100    0    0    1   15
  20  148    2   28    6   21
  21  443    5   16    1   22
  22  367    6   49    1   48</code></pre>
</div>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>resultado_chi_cuadrado <span class="ot">&lt;-</span> <span class="fu">chisq.test</span>(tabla_contingencia)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in chisq.test(tabla_contingencia): Chi-squared approximation may be
incorrect</code></pre>
</div>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>resultado_chi_cuadrado</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test

data:  tabla_contingencia
X-squared = 5855.4, df = 84, p-value &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Al realizar una tabla de contingencia y realizar un test de chi-cuadrado es posible observar que el valor de p es menor al nivel de significancia, de 0.05. Esto quiere decir que el departamento de registro de la defunción está relacionado con la asistencia recibida.</p>
</section>
<section id="la-causa-de-defunción-está-relacionada-con-las-semanas-de-gestación-de-la-madre" class="level4">
<h4 class="anchored" data-anchor-id="la-causa-de-defunción-está-relacionada-con-las-semanas-de-gestación-de-la-madre">4.4 ¿La causa de defunción está relacionada con las semanas de gestación de la madre?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a>causas_por_semana <span class="ot">&lt;-</span> <span class="fu">aggregate</span>(CAUDEF <span class="sc">~</span> SEMGES, <span class="at">data =</span> datos, <span class="cf">function</span>(x) {</span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>  causas <span class="ot">&lt;-</span> <span class="fu">table</span>(x)</span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">names</span>(causas)[<span class="fu">which.max</span>(causas)]</span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>})</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a>causas_por_semana</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>   SEMGES CAUDEF
1       1   P95X
2       2   P003
3       3   P95X
4       4   P209
5       5   P209
6       6   P95X
7       7   P95X
8       8   P95X
9       9   P95X
10     10   P95X
11     11   P018
12     12   P209
13     13   P209
14     14   P209
15     15   P95X
16     16   P95X
17     17   P95X
18     18   P209
19     19   P209
20     20   P95X
21     21   P95X
22     22   P209
23     23   P95X
24     24   P95X
25     25   P95X
26     26   P95X
27     27   P95X
28     28   P95X
29     29   P95X
30     30   P95X
31     31   P95X
32     32   P95X
33     33   P95X
34     34   P95X
35     35   P95X
36     36   P95X
37     37   P95X
38     38   P95X
39     39   P95X
40     40   P95X
41     41   P95X
42     42   P95X
43     43   P209
44     44   P95X</code></pre>
</div>
</div>
</section>
<section id="cual-es-el-promedio-de-defunciones-por-año" class="level4">
<h4 class="anchored" data-anchor-id="cual-es-el-promedio-de-defunciones-por-año">4.5 ¿Cual es el Promedio de defunciones por año?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Agrupar por año de registro</span></span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>data_grouped_anoreg <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(AÑOREG) <span class="sc">%&gt;%</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Defunciones =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el resultado</span></span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_grouped_anoreg, <span class="fu">aes</span>(<span class="at">x =</span> AÑOREG, <span class="at">y =</span> Defunciones, <span class="at">fill =</span> <span class="fu">factor</span>(AÑOREG))) <span class="sc">+</span></span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Defunciones fetales por año"</span>,</span>
<span id="cb38-12"><a href="#cb38-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Año de registro"</span>,</span>
<span id="cb38-13"><a href="#cb38-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Número de defunciones fetales"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-53-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calcular el promedio de defunciones fetales por año</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>promedio_defunciones_anuales <span class="ot">&lt;-</span> <span class="fu">mean</span>(data_grouped_anoreg<span class="sc">$</span>Defunciones)</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Mostrar el resultado</span></span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a><span class="fu">cat</span>(<span class="st">"El promedio de defunciones fetales por año es:"</span>, promedio_defunciones_anuales)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>El promedio de defunciones fetales por año es: 2774.231</code></pre>
</div>
</div>
<p>Al evaular la grafica podemos observar que la mayoria de las defunciones fetales ocurren en el departamento de Guatemala y en el municipio de Guatemala.</p>
</section>
<section id="el-estado-civil-de-la-madre-influye-en-la-probabilidad-de-una-defunción-fetal" class="level4">
<h4 class="anchored" data-anchor-id="el-estado-civil-de-la-madre-influye-en-la-probabilidad-de-una-defunción-fetal">4.6 ¿El estado civil de la madre influye en la probabilidad de una defunción fetal?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Agrupar por estado civil de la madre</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>data_grouped_escivm <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ESCIVM) <span class="sc">%&gt;%</span></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Defunciones =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizar resultados</span></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_grouped_escivm, <span class="fu">aes</span>(<span class="at">x =</span> ESCIVM, <span class="at">y =</span> Defunciones, <span class="at">fill =</span> ESCIVM)) <span class="sc">+</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb41-11"><a href="#cb41-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Defunciones fetales por estado civil de la madre"</span>,</span>
<span id="cb41-12"><a href="#cb41-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Estado civil de la madre"</span>,</span>
<span id="cb41-13"><a href="#cb41-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Número de defunciones fetales"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing missing values (`geom_bar()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-54-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Al observar la tabla podemos ver que la mayoria de las defunciones fetales ocurrieron en madres solteras.</p>
</section>
<section id="las-madres-con-más-hijos-tenidos-tienen-una-mayor-proporción-de-defunciones-fetales" class="level4">
<h4 class="anchored" data-anchor-id="las-madres-con-más-hijos-tenidos-tienen-una-mayor-proporción-de-defunciones-fetales">4.7 ¿Las madres con más hijos tenidos tienen una mayor proporción de defunciones fetales?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Agrupar por total de hijos tenidos</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>data_grouped_hijos <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(TOHITE) <span class="sc">%&gt;%</span></span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Defunciones =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizar resultados</span></span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_grouped_hijos, <span class="fu">aes</span>(<span class="at">x =</span> TOHITE, <span class="at">y =</span> Defunciones, <span class="at">fill =</span> TOHITE)) <span class="sc">+</span></span>
<span id="cb43-9"><a href="#cb43-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb43-10"><a href="#cb43-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb43-11"><a href="#cb43-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Defunciones fetales por total de hijos tenidos"</span>,</span>
<span id="cb43-12"><a href="#cb43-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Total de hijos tenidos"</span>,</span>
<span id="cb43-13"><a href="#cb43-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Número de defunciones fetales"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing missing values (`geom_bar()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-55-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Al observar el grafico podemos ver que a medida de que se tengan mas hijos es menor la probabilidad de tener una defuncion fetal.a partir de 1 hijo tenido. ya que este es el que tiene la mayor probabilidad de tener una defuncion fetal.</p>
</section>
<section id="los-sitios-de-ocurrencia-tienen-un-impacto-en-la-tasa-de-defunciones-fetales" class="level4">
<h4 class="anchored" data-anchor-id="los-sitios-de-ocurrencia-tienen-un-impacto-en-la-tasa-de-defunciones-fetales">4.8 ¿Los sitios de ocurrencia tienen un impacto en la tasa de defunciones fetales?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Agrupar por escolaridad de la madre</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>data_grouped_escolam <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(ESCOLAM) <span class="sc">%&gt;%</span></span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">Defunciones =</span> <span class="fu">n</span>()) <span class="sc">%&gt;%</span></span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizar resultados</span></span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_grouped_escolam, <span class="fu">aes</span>(<span class="at">x =</span> ESCOLAM, <span class="at">y =</span> Defunciones, <span class="at">fill =</span> <span class="fu">factor</span>(ESCOLAM))) <span class="sc">+</span></span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">position =</span> <span class="st">"dodge"</span>) <span class="sc">+</span></span>
<span id="cb45-10"><a href="#cb45-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb45-11"><a href="#cb45-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Defunciones fetales por escolaridad de la madre"</span>,</span>
<span id="cb45-12"><a href="#cb45-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Escolaridad de la madre"</span>,</span>
<span id="cb45-13"><a href="#cb45-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Número de defunciones fetales"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 1 rows containing missing values (`geom_bar()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/ESTA%20TIRA%20ERROR-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Podemos observar que la mayoria de las defunciones fetales ocurren en madres con un nivel de escolaridad baja o nula.</p>
</section>
<section id="existe-alguna-relación-entre-la-vía-del-parto-y-la-escolaridad-de-la-madre-en-las-defunciones-fetales" class="level4">
<h4 class="anchored" data-anchor-id="existe-alguna-relación-entre-la-vía-del-parto-y-la-escolaridad-de-la-madre-en-las-defunciones-fetales">4.9 ¿Existe alguna relación entre la vía del parto y la escolaridad de la madre en las defunciones fetales?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear una tabla de contingencia para el recuento de casos por vía del parto y escolaridad de la madre</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>data_grouped <span class="ot">&lt;-</span> datos <span class="sc">%&gt;%</span></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(ESCOLAM, VIAPAR) <span class="sc">%&gt;%</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">Escolaridad =</span> ESCOLAM, <span class="at">ViaParto =</span> VIAPAR, <span class="at">Casos =</span> n)</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Visualizar resultados en un gráfico de barras apiladas</span></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(data_grouped, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(Escolaridad), <span class="at">y =</span> Casos, <span class="at">fill =</span> <span class="fu">factor</span>(ViaParto))) <span class="sc">+</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>) <span class="sc">+</span></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Relación entre la vía del parto y la escolaridad de la madre en defunciones fetales"</span>,</span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Escolaridad de la madre"</span>,</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"Número de casos"</span>,</span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>       <span class="at">fill =</span> <span class="st">"Vía del parto"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-56-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se puede observar que el mes de gestacion con mayor probabilidad de tener una defuncion fetal es el mes 1, sin embargo todos los meses estan en un rango similar de probabilidad de tener una defuncion fetal.</p>
</section>
<section id="existe-alguna-relación-entre-la-semana-de-gestacíon-y-la-via-del-parto" class="level4">
<h4 class="anchored" data-anchor-id="existe-alguna-relación-entre-la-semana-de-gestacíon-y-la-via-del-parto">4.10 ¿Existe alguna relación entre la semana de gestacíon y la via del parto?</h4>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 4163 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-57-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Como se puede observar en el diagrama de caja y bigoteindica la separacion de los bigotes es considerablemente alta lo que nos indica que hay una diferencia en las semanas de gestación según la vía del parto. En otras palabras, que si existe una relación entre estas dos variables.</p>
</section>
<section id="cómo-se-distribuye-la-asistencia-médica-recibida" class="level4">
<h4 class="anchored" data-anchor-id="cómo-se-distribuye-la-asistencia-médica-recibida">4.11 ¿Cómo se distribuye la asistencia médica recibida?</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-58-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se puede observar que la mayor cantidad de veces se recibe asistencia médica, que pertenece al código 1. Luego se puede observar que varias emergencias son atendidas por una comadrona. Bastantes defunciones fetales no tuvieron asistencia alguna, lo que corresponde a la porción del código 5.</p>
</section>
<section id="cuáles-son-las-5-semanas-de-gestación-donde-más-defunciones-se-dan" class="level4">
<h4 class="anchored" data-anchor-id="cuáles-son-las-5-semanas-de-gestación-donde-más-defunciones-se-dan">4.12 ¿Cuáles son las 5 semanas de gestación donde más defunciones se dan?</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> datos[<span class="fu">complete.cases</span>(datos), ]</span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>temp <span class="ot">&lt;-</span> temp <span class="sc">%&gt;%</span></span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>        <span class="fu">group_by</span>(SEMGES) <span class="sc">%&gt;%</span></span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>        <span class="fu">summarise</span>(<span class="at">count=</span><span class="fu">n</span>())</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>top_semanas <span class="ot">&lt;-</span> temp <span class="sc">%&gt;%</span></span>
<span id="cb49-7"><a href="#cb49-7" aria-hidden="true" tabindex="-1"></a>      <span class="fu">top_n</span>(<span class="at">n=</span><span class="dv">5</span>, <span class="at">wt=</span>count)</span>
<span id="cb49-8"><a href="#cb49-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb49-9"><a href="#cb49-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(top_semanas, <span class="fu">aes</span>(<span class="at">x =</span> SEMGES, <span class="at">y =</span> count)) <span class="sc">+</span></span>
<span id="cb49-10"><a href="#cb49-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat =</span> <span class="st">"identity"</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>) <span class="sc">+</span></span>
<span id="cb49-11"><a href="#cb49-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggtitle</span>(<span class="st">"Top 5 semanas con más defunciones"</span>) <span class="sc">+</span></span>
<span id="cb49-12"><a href="#cb49-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Semanas de gestación"</span>) <span class="sc">+</span></span>
<span id="cb49-13"><a href="#cb49-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ylab</span>(<span class="st">"Número de defunciones"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-59-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Las semanas donde más defunciones se dan van de la 36 a la 50. La mayor cantidad de defunciones se da en la semana 40, la cual es una semana bastante tardía.</p>
</section>
<section id="cuál-es-la-frecuencia-del-sitio-de-ocurrencia-de-los-partos" class="level4">
<h4 class="anchored" data-anchor-id="cuál-es-la-frecuencia-del-sitio-de-ocurrencia-de-los-partos">4.13 ¿Cuál es la frecuencia del sitio de ocurrencia de los partos?</h4>
<div class="cell">
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-60-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>La mayoría de defunciones se dán en hospitales públicos. Este dato es importante, porque puede indicar alguna deficiencia en este tipo de hospitales. Interesantemente, la siguiente categoría en defunciones fetales es en domicilios, correspondiente al código 6. El seguro social y hospitales privados reportan una cantidad muy similar de defunciones.</p>
</section>
</section>
</section>
<section id="clustering" class="level2">
<h2 class="anchored" data-anchor-id="clustering">5. Clustering</h2>
<section id="determinar-si-vale-la-pena-agrupar" class="level3">
<h3 class="anchored" data-anchor-id="determinar-si-vale-la-pena-agrupar">5.1 Determinar si vale la pena agrupar</h3>
<div class="cell">

</div>
<p>Se calculó el estadístico de Hopkins para determinar si es válido agrupar los datos. El valor de este es de 1, por lo que si vale la pena intentar un agrupamiento.</p>
</section>
<section id="determinar-la-cantidad-de-grupos-para-el-cluster" class="level3">
<h3 class="anchored" data-anchor-id="determinar-la-cantidad-de-grupos-para-el-cluster">5.2 Determinar la cantidad de grupos para el cluster</h3>
<section id="metodo-de-wss-y-silueta" class="level4">
<h4 class="anchored" data-anchor-id="metodo-de-wss-y-silueta">Metodo de wss y silueta</h4>
<div class="cell">
<div class="cell-output cell-output-stderr">
<pre><code>Warning in plot.xy(xy, type, ...): plot type 'bow' will be truncated to first
character</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/metodo_wss-1.png" class="img-fluid" width="672"></p>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/metodo_wss-2.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Es posible observar de la gráfica del codo que la cantidad de grupos óptima son 3. La silueta indica lo mismo, así que se procederá a realizar esta cantidad.</p>
</section>
</section>
<section id="por-k-medias" class="level3">
<h3 class="anchored" data-anchor-id="por-k-medias">5.3 Por k medias</h3>
<section id="agrupamiento" class="level4">
<h4 class="anchored" data-anchor-id="agrupamiento">5.3.1 Agrupamiento</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>km <span class="ot">&lt;-</span> <span class="fu">kmeans</span>(numericas_norm, <span class="at">centers =</span> <span class="dv">3</span>, <span class="at">iter.max =</span> <span class="dv">100</span>)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a><span class="co"># find number of observations in each cluster</span></span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(km<span class="sc">$</span>cluster)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
   1    2    3 
3507 6657 6880 </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="fu">fviz_cluster</span>(km, numericas_norm)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-62-1.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="calidad-del-agrupamiento-segun-el-método-de-la-silueta" class="level4">
<h4 class="anchored" data-anchor-id="calidad-del-agrupamiento-segun-el-método-de-la-silueta">5.3.2 Calidad del agrupamiento segun el método de la silueta</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>m <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">withinss =</span> km<span class="sc">$</span>withinss, <span class="at">size =</span> km<span class="sc">$</span>size)</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(m, <span class="fu">aes</span>(size, withinss)) <span class="sc">+</span></span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_point</span>() <span class="sc">+</span></span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>) <span class="sc">+</span></span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a>    <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"cardinalidad (size)"</span>, <span class="at">y =</span> <span class="st">"magnitud (whithinss)"</span>) <span class="sc">+</span></span>
<span id="cb54-7"><a href="#cb54-7" aria-hidden="true" tabindex="-1"></a>    <span class="fu">geom_text_repel</span>(<span class="at">label =</span> <span class="fu">rownames</span>(m))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>`geom_smooth()` using formula = 'y ~ x'</code></pre>
</div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-63-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>silueta <span class="ot">&lt;-</span> <span class="fu">silhouette</span>(km<span class="sc">$</span>cluster, distancia)</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>mean <span class="ot">&lt;-</span> <span class="fu">mean</span>(silueta[, <span class="dv">3</span>])</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a>mean</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.3748498</code></pre>
</div>
</div>
<p>La silueta es de 0.37, lo cual es un valor relativamente alto que indica que con 3 grupos se genera un agrupamiento aceptable.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> <span class="fu">kcca</span>(numericas_norm, <span class="dv">3</span>)</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>importance <span class="ot">&lt;-</span> <span class="fu">FeatureImpCluster</span>(res, <span class="fu">as.data.table</span>(numericas_norm))</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(importance)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-64-1.png" class="img-fluid" width="672"></p>
</div>
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="fu">barplot</span>(res, <span class="at">bycluster =</span> T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Proyecto_files/figure-html/unnamed-chunk-64-2.png" class="img-fluid" width="672"></p>
</div>
</div>
</section>
<section id="clasificacion-de-los-grupos" class="level4">
<h4 class="anchored" data-anchor-id="clasificacion-de-los-grupos">5.3.3 Clasificacion de los grupos</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> datos[<span class="fu">complete.cases</span>(numericas_temp), ]</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>df<span class="sc">$</span>grupo <span class="ot">&lt;-</span> km<span class="sc">$</span>cluster</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>grupo1 <span class="ot">&lt;-</span> df[df<span class="sc">$</span>grupo <span class="sc">==</span> <span class="dv">1</span>,]</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>grupo2 <span class="ot">&lt;-</span> df[df<span class="sc">$</span>grupo <span class="sc">==</span> <span class="dv">2</span>,]</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>grupo3 <span class="ot">&lt;-</span> df[df<span class="sc">$</span>grupo <span class="sc">==</span> <span class="dv">3</span>,]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="grupo-1" class="level5">
<h5 class="anchored" data-anchor-id="grupo-1">Grupo 1</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(grupo1[,numericas])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     SEMGES         EDADM           TOHITE           TOHINM     
 Min.   : 1.0   Min.   :11.00   Min.   : 1.000   Min.   :1.000  
 1st Qu.:24.0   1st Qu.:23.00   1st Qu.: 2.000   1st Qu.:1.000  
 Median :27.0   Median :28.00   Median : 3.000   Median :1.000  
 Mean   :26.4   Mean   :27.67   Mean   : 3.068   Mean   :1.225  
 3rd Qu.:30.0   3rd Qu.:32.00   3rd Qu.: 4.000   3rd Qu.:1.000  
 Max.   :33.0   Max.   :45.00   Max.   :11.000   Max.   :9.000  
     TOHIVI      
 Min.   : 0.000  
 1st Qu.: 1.000  
 Median : 1.000  
 Mean   : 1.843  
 3rd Qu.: 2.000  
 Max.   :10.000  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(grupo1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   3507 obs. of  26 variables:
 $ DEPREG  : Factor w/ 22 levels "1","2","3","4",..: 1 10 10 7 8 16 7 7 9 9 ...
 $ MUPREG  : Factor w/ 334 levels "101","102","103",..: 1 156 149 86 107 264 89 90 129 119 ...
 $ MESREG  : Factor w/ 12 levels "1","2","3","4",..: 12 4 3 12 7 8 3 3 1 1 ...
 $ AÑOREG  : Factor w/ 13 levels "2010","2011",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ DEPOCU  : Factor w/ 22 levels "1","2","3","4",..: 1 10 10 7 8 16 7 7 9 9 ...
 $ MUPOCU  : Factor w/ 309 levels "101","102","103",..: 1 148 141 80 101 250 83 84 123 113 ...
 $ SEXO    : int  2 1 1 1 1 1 1 2 1 1 ...
 $ DIAOCU  : Factor w/ 31 levels "1","2","3","4",..: 18 1 28 31 19 22 22 6 24 11 ...
 $ MESOCU  : Factor w/ 12 levels "1","2","3","4",..: 12 4 3 12 7 7 3 3 1 1 ...
 $ TIPAR   : Factor w/ 3 levels "1","2","3": 1 1 1 1 1 1 1 1 1 1 ...
 $ CLAPAR  : Factor w/ 2 levels "1","2": 1 1 1 1 1 2 1 1 1 1 ...
 $ VIAPAR  : Factor w/ 2 levels "1","2": 1 1 1 1 1 2 1 1 1 1 ...
 $ SEMGES  : int  1 1 1 5 6 7 9 9 9 9 ...
 $ EDADM   : int  19 36 19 38 28 32 38 28 45 22 ...
 $ DEPREM  : int  2 1 1 1 1 1 1 2 1 1 ...
 $ MUPREM  : int  2 1 1 1 1 1 1 2 1 1 ...
 $ ESCIVM  : int  2 1 1 1 1 1 1 2 1 1 ...
 $ NACIOM  : int  2 1 1 1 1 1 1 2 1 1 ...
 $ ESCOLAM : int  3 NA 1 2 1 1 1 1 2 NA ...
 $ CAUDEF  : Factor w/ 184 levels "","B24X","P000",..: 63 117 117 63 117 117 117 117 178 117 ...
 $ ASISREC : Factor w/ 5 levels "1","2","3","4",..: 1 3 3 1 3 4 3 3 5 5 ...
 $ SITIOOCU: int  1 6 6 1 6 6 6 6 6 6 ...
 $ TOHITE  : int  2 11 2 9 7 7 3 4 8 3 ...
 $ TOHINM  : int  1 3 1 1 1 1 1 1 2 2 ...
 $ TOHIVI  : int  1 8 1 8 6 6 2 3 6 1 ...
 $ grupo   : int  1 1 1 1 1 1 1 1 1 1 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo1<span class="sc">$</span>DEPREG))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
         1         16          4         14          9          7         13 
39.8346165  7.1571143  6.4727687  5.8739664  5.7884232  4.2201312  3.7639008 
         3          8         15          5         11         10         12 
 3.2221272  3.0795552  3.0795552  2.9084688  2.6803536  2.3381808  2.1100656 
        17         21         22          2          6         18         20 
 1.7108640  1.4542344  1.2831480  0.9409752  0.8269176  0.6558312  0.3421728 
        19 
 0.2566296 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo1<span class="sc">$</span>TIPAR))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        1         2         3 
93.213573  6.643855  0.142572 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo1<span class="sc">$</span>CLAPAR))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
76.81779 23.18221 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb71"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb71-1"><a href="#cb71-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo1<span class="sc">$</span>VIAPAR))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
77.01739 22.98261 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb73"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb73-1"><a href="#cb73-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo1<span class="sc">$</span>DEPREM))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
53.04348 46.95652 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb75"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb75-1"><a href="#cb75-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo1<span class="sc">$</span>ESCIVM))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
53.04948 46.95052 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb77"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb77-1"><a href="#cb77-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo1<span class="sc">$</span>ESCOLAM))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
          2           1           4           3           5           6 
39.18674699 25.93373494 18.22289157 14.30722892  2.31927711  0.03012048 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb79"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb79-1"><a href="#cb79-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo1<span class="sc">$</span>SEXO))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
52.98851 47.01149 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb81"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb81-1"><a href="#cb81-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo1<span class="sc">$</span>MESREG))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       7        5        8        1       10        4       11        6 
9.438266 9.181637 8.839464 8.725406 8.725406 8.411748 8.326205 8.155118 
       9        3        2       12 
7.812946 7.755917 7.727402 6.900485 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb83"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb83-1"><a href="#cb83-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo1<span class="sc">$</span>NACIOM))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
52.99194 47.00806 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb85"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb85-1"><a href="#cb85-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo1<span class="sc">$</span>CAUDEF))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
      P95X       P209       P073       Q897       Q899       P021       P000 
43.0282293 31.6224693  3.9920160  2.1385800  2.0815512  1.8249216  1.2831480 
      Q000       P012       P022       P025       P964       P832       P011 
 1.2831480  1.1405760  1.1405760  0.9980040  0.6843456  0.6558312  0.5988024 
      P027       P070       P072       P020       P024       P220       P018 
 0.5988024  0.5417736  0.5417736  0.4562304  0.4562304  0.3992016  0.3706872 
      P013       P010       P001       P008       Q039       P038       P015 
 0.3421728  0.3136584  0.2281152  0.2281152  0.1996008  0.1710864  0.1425720 
      P017       P026       P240       Q249       P009       P035       P050 
 0.1425720  0.1425720  0.1140576  0.1140576  0.0855432  0.0855432  0.0855432 
      Q043       Q606       Q793       P005       P007       P019       P023 
 0.0855432  0.0855432  0.0855432  0.0570288  0.0570288  0.0570288  0.0570288 
      P031       P280       P369       P550       P702       Q019       Q049 
 0.0570288  0.0570288  0.0570288  0.0570288  0.0570288  0.0570288  0.0570288 
      B24X       P002       P004       P014       P029       P043       P100 
 0.0285144  0.0285144  0.0285144  0.0285144  0.0285144  0.0285144  0.0285144 
      P158       P159       P210       P285       P292       P351       P741 
 0.0285144  0.0285144  0.0285144  0.0285144  0.0285144  0.0285144  0.0285144 
      P77X       P788       P819       P835       Q010       Q012       Q031 
 0.0285144  0.0285144  0.0285144  0.0285144  0.0285144  0.0285144  0.0285144 
      Q059       Q079       Q240       Q248       Q359       Q390       Q410 
 0.0285144  0.0285144  0.0285144  0.0285144  0.0285144  0.0285144  0.0285144 
      Q769       Q868       Q892                  P003       P016       P028 
 0.0285144  0.0285144  0.0285144  0.0000000  0.0000000  0.0000000  0.0000000 
      P030       P034       P036       P039       P051       P052       P059 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000 
      P080       P081       P082       P103       P109       P112       P119 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000 
      P130       P131       P138       P150       P200       P201       P219 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000 
      P228       P229       P239       P241       P249       P250       P251 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000 
      P269       P288       P290       P291       P293       P371       P392 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000 
      P509       P518       P523       P524       P525       P528       P529 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000 
      P546       P548       P558       P569       P60X       P614       P700 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000 
      P701       P704       P708       P709       P721       P740       P916 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000 
      P941       P968       P969       Q001       Q02X       Q042       Q048 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000 
      Q204       Q213       Q218       Q278       Q336       Q369       Q379 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000 
      Q423       Q433       Q529       Q564       Q602       Q611       Q614 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000 
      Q639       Q678       Q688       Q742       Q753       Q758       Q759 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000 
      Q764       Q774       Q790       Q792       Q795       Q860       Q870 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000 
      Q871       Q872       Q898       Q909       Q911       Q913       Q917 
 0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000  0.0000000 
      Q999       W499 
 0.0000000  0.0000000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb87"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb87-1"><a href="#cb87-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo1<span class="sc">$</span>ASISREC))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        1         5         3         2         4 
84.431138  8.069575  6.928999  0.427716  0.142572 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb89"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb89-1"><a href="#cb89-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo1<span class="sc">$</span>SITIOOCU))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
          1           6           4           2           3           5 
65.36755387 12.70595691 12.26235741  7.35107731  2.12294043  0.09505703 
          8 
 0.09505703 </code></pre>
</div>
</div>
<p>Características principales del grupo:</p>
<ul>
<li>Las semanas de gestación en las que se produjo la defunción van de 1 a 33. El 50% de las defunciones se produjeron abajo de la semana 27.</li>
<li>La edad promedio de las madres es de 27 años. Siendo la edad mínima 11 y la máxima 45.</li>
<li>La cantidad de hijos tenidos para el grupo va de 1 a 11, siendo el promedio de 3. El 50% de las observaciones están por debajo de los 3 hijos tenidos.</li>
<li>La cantidad de hijos vivos en promedio es 1 hijo, siendo que el 75% de las mujeres solo tienen 2 hijos vivos o menos.</li>
<li>En este grupo la mayoría de mujeres tienen 1 hijo en el parto y un 6.6% tienen 2.</li>
<li>En este grupo la mayoría de mujeres, un 39%, tienen una educación primaria. Un 26% tienen educación nula.</li>
</ul>
<p>Con las caracteristicas mencionadas anteriormente podemos denotar a este grupo como “grupo de madres jovenes que tuvieron una defunción temprana, mayormente con educación primaria”.</p>
</section>
<section id="grupo-2" class="level5">
<h5 class="anchored" data-anchor-id="grupo-2">Grupo 2</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb91"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb91-1"><a href="#cb91-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(grupo2[,numericas])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     SEMGES          EDADM           TOHITE           TOHINM     
 Min.   :30.00   Min.   :14.00   Min.   : 1.000   Min.   :1.000  
 1st Qu.:36.00   1st Qu.:22.00   1st Qu.: 2.000   1st Qu.:1.000  
 Median :38.00   Median :25.00   Median : 3.000   Median :1.000  
 Mean   :37.44   Mean   :24.91   Mean   : 2.868   Mean   :1.155  
 3rd Qu.:40.00   3rd Qu.:28.00   3rd Qu.: 4.000   3rd Qu.:1.000  
 Max.   :44.00   Max.   :32.00   Max.   :12.000   Max.   :7.000  
     TOHIVI     
 Min.   :0.000  
 1st Qu.:1.000  
 Median :1.000  
 Mean   :1.713  
 3rd Qu.:2.000  
 Max.   :9.000  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb93"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb93-1"><a href="#cb93-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(grupo2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   6657 obs. of  26 variables:
 $ DEPREG  : Factor w/ 22 levels "1","2","3","4",..: 13 1 1 16 1 1 1 1 1 1 ...
 $ MUPREG  : Factor w/ 334 levels "101","102","103",..: 197 1 1 257 1 1 1 1 1 1 ...
 $ MESREG  : Factor w/ 12 levels "1","2","3","4",..: 12 7 2 9 11 9 11 11 12 12 ...
 $ AÑOREG  : Factor w/ 13 levels "2010","2011",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ DEPOCU  : Factor w/ 22 levels "1","2","3","4",..: 13 1 1 16 1 1 1 1 1 1 ...
 $ MUPOCU  : Factor w/ 309 levels "101","102","103",..: 188 1 1 243 1 1 1 1 1 1 ...
 $ SEXO    : int  2 1 2 1 2 1 2 1 1 2 ...
 $ DIAOCU  : Factor w/ 31 levels "1","2","3","4",..: 16 23 7 28 2 5 17 22 23 29 ...
 $ MESOCU  : Factor w/ 12 levels "1","2","3","4",..: 12 7 2 9 11 9 11 11 12 12 ...
 $ TIPAR   : Factor w/ 3 levels "1","2","3": 1 1 1 1 1 1 1 1 1 1 ...
 $ CLAPAR  : Factor w/ 2 levels "1","2": 1 2 1 1 1 1 1 1 1 1 ...
 $ VIAPAR  : Factor w/ 2 levels "1","2": 1 2 1 1 1 1 1 1 1 1 ...
 $ SEMGES  : int  30 30 31 31 31 32 32 32 32 32 ...
 $ EDADM   : int  16 18 22 21 21 21 25 21 22 25 ...
 $ DEPREM  : int  2 NA 2 1 NA 1 2 1 1 2 ...
 $ MUPREM  : int  2 NA 2 1 NA 1 2 1 1 2 ...
 $ ESCIVM  : int  2 1 2 1 2 1 2 1 1 2 ...
 $ NACIOM  : int  2 1 2 1 2 1 2 1 1 2 ...
 $ ESCOLAM : int  NA NA NA 2 NA 1 1 3 NA 3 ...
 $ CAUDEF  : Factor w/ 184 levels "","B24X","P000",..: 178 63 121 117 23 63 117 63 23 117 ...
 $ ASISREC : Factor w/ 5 levels "1","2","3","4",..: 1 1 1 1 5 1 1 1 1 1 ...
 $ SITIOOCU: int  1 1 1 1 6 1 4 1 2 1 ...
 $ TOHITE  : int  2 2 2 2 2 3 2 2 2 3 ...
 $ TOHINM  : int  1 1 1 1 1 1 1 1 1 2 ...
 $ TOHIVI  : int  1 1 1 1 1 2 1 1 1 1 ...
 $ grupo   : int  2 2 2 2 2 2 2 2 2 2 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb95"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb95-1"><a href="#cb95-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo2<span class="sc">$</span>DEPREG))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
         1         16         14          4          9          7         13 
18.6119874 17.6806369  9.8693105  6.3692354  5.9336037  5.4228632  5.0022533 
         5          8         10         15          3         12         21 
 4.4764909  4.4164038  3.8005107  3.1545741  2.2983326  2.2232237  1.8777227 
        11         22         17          2          6         18         20 
 1.8176356  1.7275049  1.6223524  1.1116118  0.9313505  0.7060237  0.5708277 
        19 
 0.3755445 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb97"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb97-1"><a href="#cb97-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo2<span class="sc">$</span>TIPAR))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
          1           2           3 
96.04927144  3.86059787  0.09013069 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb99"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb99-1"><a href="#cb99-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo2<span class="sc">$</span>CLAPAR))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
73.23119 26.76881 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb101"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb101-1"><a href="#cb101-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo2<span class="sc">$</span>VIAPAR))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
73.36638 26.63362 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb103"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb103-1"><a href="#cb103-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo2<span class="sc">$</span>DEPREM))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
52.22814 47.77186 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb105"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb105-1"><a href="#cb105-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo2<span class="sc">$</span>ESCIVM))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
52.17719 47.82281 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb107"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb107-1"><a href="#cb107-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo2<span class="sc">$</span>ESCOLAM))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
          2           1           3           4           5           6 
42.73218830 35.05089059 11.70483461  9.81234097  0.68384224  0.01590331 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb109"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb109-1"><a href="#cb109-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo2<span class="sc">$</span>SEXO))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
52.15952 47.84048 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb111"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb111-1"><a href="#cb111-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo2<span class="sc">$</span>MESREG))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1       10        8        5        7       12        9       11 
9.238396 9.028091 8.727655 8.682590 8.637524 8.427219 8.367132 8.231936 
       4        2        6        3 
8.111762 7.601021 7.601021 7.345651 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb113"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb113-1"><a href="#cb113-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo2<span class="sc">$</span>NACIOM))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
52.16998 47.83002 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb115"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb115-1"><a href="#cb115-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo2<span class="sc">$</span>CAUDEF))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       P95X        P209        Q000        P025        Q897        P964 
46.47739222 33.58870362  1.77257023  1.74252666  1.69746132  1.39702569 
       Q899        P017        P021        P012        P000        P073 
 1.29187322  1.21676431  1.15667718  0.94637224  0.91632868  0.88628511 
       P022        P024        P031        P240        P038        P013 
 0.69100195  0.69100195  0.60087126  0.60087126  0.58584948  0.25537029 
       P020        Q039        P027        P158        P011        P832 
 0.25537029  0.21030494  0.19528316  0.15021782  0.13519603  0.13519603 
       P018        P026        P702        Q249        P001        P220 
 0.12017425  0.10515247  0.10515247  0.10515247  0.09013069  0.09013069 
       Q043        Q059        P008        P051        P059        P015 
 0.09013069  0.09013069  0.07510891  0.07510891  0.07510891  0.06008713 
       P080        P369        Q031        Q606        P002        P009 
 0.06008713  0.06008713  0.06008713  0.06008713  0.04506534  0.04506534 
       P701        P004        P005        P019        P035        P036 
 0.04506534  0.03004356  0.03004356  0.03004356  0.03004356  0.03004356 
       P070        P292        P550        Q336        Q758        Q793 
 0.03004356  0.03004356  0.03004356  0.03004356  0.03004356  0.03004356 
       Q909        Q999        P023        P029        P034        P050 
 0.03004356  0.03004356  0.01502178  0.01502178  0.01502178  0.01502178 
       P052        P081        P082        P103        P119        P130 
 0.01502178  0.01502178  0.01502178  0.01502178  0.01502178  0.01502178 
       P138        P150        P200        P201        P229        P250 
 0.01502178  0.01502178  0.01502178  0.01502178  0.01502178  0.01502178 
       P285        P288        P291        P518        P529        P569 
 0.01502178  0.01502178  0.01502178  0.01502178  0.01502178  0.01502178 
       P614        P708        P709        P941        P968        Q001 
 0.01502178  0.01502178  0.01502178  0.01502178  0.01502178  0.01502178 
       Q019        Q02X        Q049        Q248        Q410        Q602 
 0.01502178  0.01502178  0.01502178  0.01502178  0.01502178  0.01502178 
       Q753        Q774        Q913                    B24X        P003 
 0.01502178  0.01502178  0.01502178  0.00000000  0.00000000  0.00000000 
       P007        P010        P014        P016        P028        P030 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       P039        P043        P072        P100        P109        P112 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       P131        P159        P210        P219        P228        P239 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       P241        P249        P251        P269        P280        P290 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       P293        P351        P371        P392        P509        P523 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       P524        P525        P528        P546        P548        P558 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       P60X        P700        P704        P721        P740        P741 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       P77X        P788        P819        P835        P916        P969 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       Q010        Q012        Q042        Q048        Q079        Q204 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       Q213        Q218        Q240        Q278        Q359        Q369 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       Q379        Q390        Q423        Q433        Q529        Q564 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       Q611        Q614        Q639        Q678        Q688        Q742 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       Q759        Q764        Q769        Q790        Q792        Q795 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       Q860        Q868        Q870        Q871        Q872        Q892 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       Q898        Q911        Q917        W499 
 0.00000000  0.00000000  0.00000000  0.00000000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb117"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb117-1"><a href="#cb117-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo2<span class="sc">$</span>ASISREC))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
        1         3         5         2         4 
71.248310 19.032597  7.856392  1.036503  0.826198 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb119"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb119-1"><a href="#cb119-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo2<span class="sc">$</span>SITIOOCU))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
          1           6           2           4           3           8 
58.68904876 27.01838529  5.78737010  4.94004796  3.37330136  0.11191047 
          5           7 
 0.06394884  0.01598721 </code></pre>
</div>
</div>
<p>Características principales del grupo:</p>
<ul>
<li>Las semanas de gestación en las que se produjo la defunción van de 30 a 44. El 50% de las defunciones fueron abajo de la semana 38.</li>
<li>La edad promedio de la mujer era de 25 años. Siendo la edad mínima 14 y la máxima 32. Teniendo que el 75% de las mujeres tenian menos de 28 años.</li>
<li>La cantidad de hijos tenidos para el grupo va de 1 a 12, siendo el promedio de 3. El 50% de las observaciones están por debajo de los 3 hijos tenidos, al igual que el grupo 2.</li>
<li>La media de la cantidad de hijos vivos es de 1 hijo. El 50% de las observaciones están por debajo de los 2 hijos vivos.</li>
<li>En este grupo la mayoría de mujeres tienen 1 hijo en el parto y un 3.86% tienen 2.</li>
<li>En este grupo la mayoría de mujeres, un 42%, tienen una educación primaria. Un 35% tienen educación nula.</li>
</ul>
<p>Con las caracteristicas mencionadas anteriormente podemos denotar a este grupo como “grupo de madres jovenes que tuvieron una defunción tardía, mayormente con educación primaria y nula”.</p>
</section>
<section id="grupo-3" class="level5">
<h5 class="anchored" data-anchor-id="grupo-3">Grupo 3</h5>
<div class="cell">
<div class="sourceCode cell-code" id="cb121"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb121-1"><a href="#cb121-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(grupo3[,numericas])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>     SEMGES          EDADM           TOHITE          TOHINM      
 Min.   :22.00   Min.   :29.00   Min.   : 1.00   Min.   : 1.000  
 1st Qu.:35.00   1st Qu.:34.00   1st Qu.: 4.00   1st Qu.: 1.000  
 Median :38.00   Median :36.00   Median : 5.00   Median : 1.000  
 Mean   :36.78   Mean   :36.73   Mean   : 5.58   Mean   : 1.512  
 3rd Qu.:40.00   3rd Qu.:39.00   3rd Qu.: 7.00   3rd Qu.: 2.000  
 Max.   :44.00   Max.   :57.00   Max.   :32.00   Max.   :30.000  
     TOHIVI      
 Min.   : 0.000  
 1st Qu.: 2.000  
 Median : 4.000  
 Mean   : 4.068  
 3rd Qu.: 6.000  
 Max.   :16.000  </code></pre>
</div>
<div class="sourceCode cell-code" id="cb123"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb123-1"><a href="#cb123-1" aria-hidden="true" tabindex="-1"></a><span class="fu">str</span>(grupo3)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>'data.frame':   6880 obs. of  26 variables:
 $ DEPREG  : Factor w/ 22 levels "1","2","3","4",..: 1 8 3 5 1 1 1 4 4 5 ...
 $ MUPREG  : Factor w/ 334 levels "101","102","103",..: 1 109 26 63 1 1 1 42 42 58 ...
 $ MESREG  : Factor w/ 12 levels "1","2","3","4",..: 6 5 5 7 5 8 8 6 7 3 ...
 $ AÑOREG  : Factor w/ 13 levels "2010","2011",..: 1 1 1 1 1 1 1 1 1 1 ...
 $ DEPOCU  : Factor w/ 22 levels "1","2","3","4",..: 1 8 3 5 1 1 1 4 4 5 ...
 $ MUPOCU  : Factor w/ 309 levels "101","102","103",..: 1 103 25 59 1 1 1 38 38 54 ...
 $ SEXO    : int  2 1 NA 2 2 1 1 1 2 1 ...
 $ DIAOCU  : Factor w/ 31 levels "1","2","3","4",..: 28 11 11 14 8 3 3 24 29 5 ...
 $ MESOCU  : Factor w/ 12 levels "1","2","3","4",..: 6 5 5 7 5 8 8 6 7 3 ...
 $ TIPAR   : Factor w/ 3 levels "1","2","3": 1 1 1 1 1 1 2 1 1 1 ...
 $ CLAPAR  : Factor w/ 2 levels "1","2": 1 1 1 2 1 2 2 1 1 1 ...
 $ VIAPAR  : Factor w/ 2 levels "1","2": 1 1 1 2 1 2 2 1 1 1 ...
 $ SEMGES  : int  23 24 25 27 28 28 28 28 28 28 ...
 $ EDADM   : int  43 46 41 44 39 37 37 38 45 41 ...
 $ DEPREM  : int  2 1 NA 2 2 1 1 1 2 1 ...
 $ MUPREM  : int  2 1 NA 2 2 1 1 1 2 1 ...
 $ ESCIVM  : int  2 1 NA 2 2 1 1 1 2 1 ...
 $ NACIOM  : int  2 1 NA 2 2 1 1 1 2 1 ...
 $ ESCOLAM : int  NA 1 1 1 1 NA NA NA 1 NA ...
 $ CAUDEF  : Factor w/ 184 levels "","B24X","P000",..: 29 117 63 19 117 63 63 117 117 63 ...
 $ ASISREC : Factor w/ 5 levels "1","2","3","4",..: 1 5 1 1 1 1 1 1 1 1 ...
 $ SITIOOCU: int  4 6 1 1 1 1 1 1 1 4 ...
 $ TOHITE  : int  6 11 4 6 7 9 9 5 13 8 ...
 $ TOHINM  : int  5 1 1 1 1 7 7 1 2 1 ...
 $ TOHIVI  : int  1 10 3 5 6 2 2 4 11 7 ...
 $ grupo   : int  3 3 3 3 3 3 3 3 3 3 ...</code></pre>
</div>
<div class="sourceCode cell-code" id="cb125"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb125-1"><a href="#cb125-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo3<span class="sc">$</span>DEPREG))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
         1         16         14          4          7          9          8 
18.4302326 16.7877907  9.6511628  7.7325581  7.5290698  5.9593023  5.2034884 
        13         15          5         10         12          3         21 
 4.7674419  3.0232558  2.9796512  2.8197674  2.6017442  2.4854651  1.7877907 
        22         17         11          2          6         18         20 
 1.7151163  1.5406977  1.4680233  0.8866279  0.8720930  0.8430233  0.6395349 
        19 
 0.2761628 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo3<span class="sc">$</span>TIPAR))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
          1           2           3 
97.20930233  2.74709302  0.04360465 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo3<span class="sc">$</span>CLAPAR))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
73.93895 26.06105 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo3<span class="sc">$</span>VIAPAR))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
74.01163 25.98837 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb133"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb133-1"><a href="#cb133-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo3<span class="sc">$</span>DEPREM))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
53.54066 46.45934 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb135"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb135-1"><a href="#cb135-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo3<span class="sc">$</span>ESCIVM))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
53.48397 46.51603 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb137"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb137-1"><a href="#cb137-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo3<span class="sc">$</span>ESCOLAM))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
          1           2           4           3           5           6 
53.74139250 33.00688600  7.78882938  3.81025249  1.63733741  0.01530222 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb139"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb139-1"><a href="#cb139-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo3<span class="sc">$</span>SEXO))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
53.46434 46.53566 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb141"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb141-1"><a href="#cb141-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo3<span class="sc">$</span>MESREG))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2       10       11        7        5        8        9 
9.156977 8.793605 8.793605 8.619186 8.575581 8.502907 8.372093 8.372093 
       6       12        3        4 
8.110465 7.979651 7.616279 7.107558 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb143"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb143-1"><a href="#cb143-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo3<span class="sc">$</span>NACIOM))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       1        2 
53.48973 46.51027 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb145"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb145-1"><a href="#cb145-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo3<span class="sc">$</span>CAUDEF))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
       P95X        P209        Q897        Q899        P021        P000 
45.72674419 32.65988372  1.91860465  1.75872093  1.65697674  1.56976744 
       P025        P964        Q000        P073        P012        P022 
 1.49709302  1.48255814  1.40988372  1.04651163  0.95930233  0.74127907 
       P038        P024        P017        P240        P031        P013 
 0.68313953  0.66860465  0.63953488  0.56686047  0.55232558  0.27616279 
       P702        P020        P008        P027        P059        P009 
 0.23255814  0.21802326  0.18895349  0.18895349  0.15988372  0.14534884 
       P832        Q039        P011        P015        P158        P220 
 0.14534884  0.14534884  0.13081395  0.13081395  0.13081395  0.13081395 
       P369        P019        P080        P001        P026        Q249 
 0.13081395  0.11627907  0.11627907  0.08720930  0.08720930  0.08720930 
       Q909        P072        P292        Q606        P081        P700 
 0.08720930  0.07267442  0.07267442  0.07267442  0.05813953  0.05813953 
       P708        Q043        Q759        P018        P030        P035 
 0.05813953  0.05813953  0.05813953  0.04360465  0.04360465  0.04360465 
       P036        P052        Q031        P005        P010        P219 
 0.04360465  0.04360465  0.04360465  0.02906977  0.02906977  0.02906977 
       P241        P285        P524        P709        P819        P969 
 0.02906977  0.02906977  0.02906977  0.02906977  0.02906977  0.02906977 
       Q049        Q059        Q336        Q410        P002        P003 
 0.02906977  0.02906977  0.02906977  0.02906977  0.01453488  0.01453488 
       P039        P043        P051        P070        P082        P159 
 0.01453488  0.01453488  0.01453488  0.01453488  0.01453488  0.01453488 
       P251        P290        P291        P392        P550        P701 
 0.01453488  0.01453488  0.01453488  0.01453488  0.01453488  0.01453488 
       P740        P968        Q019        Q02X        Q204        Q278 
 0.01453488  0.01453488  0.01453488  0.01453488  0.01453488  0.01453488 
       Q614        Q792        Q793        Q898        Q911        Q999 
 0.01453488  0.01453488  0.01453488  0.01453488  0.01453488  0.01453488 
                   B24X        P004        P007        P014        P016 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       P023        P028        P029        P034        P050        P100 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       P103        P109        P112        P119        P130        P131 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       P138        P150        P200        P201        P210        P228 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       P229        P239        P249        P250        P269        P280 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       P288        P293        P351        P371        P509        P518 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       P523        P525        P528        P529        P546        P548 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       P558        P569        P60X        P614        P704        P721 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       P741        P77X        P788        P835        P916        P941 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       Q001        Q010        Q012        Q042        Q048        Q079 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       Q213        Q218        Q240        Q248        Q359        Q369 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       Q379        Q390        Q423        Q433        Q529        Q564 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       Q602        Q611        Q639        Q678        Q688        Q742 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       Q753        Q758        Q764        Q769        Q774        Q790 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       Q795        Q860        Q868        Q870        Q871        Q872 
 0.00000000  0.00000000  0.00000000  0.00000000  0.00000000  0.00000000 
       Q892        Q913        Q917        W499 
 0.00000000  0.00000000  0.00000000  0.00000000 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb147"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb147-1"><a href="#cb147-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo3<span class="sc">$</span>ASISREC))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
         1          3          5          2          4 
73.0959302 17.8052326  7.8343023  0.6686047  0.5959302 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb149"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb149-1"><a href="#cb149-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">prop.table</span>(<span class="fu">table</span>(grupo3<span class="sc">$</span>SITIOOCU))<span class="sc">*</span><span class="dv">100</span>, <span class="at">decreasing=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
          1           6           2           4           3           5 
60.65135305 25.04719950  6.65512901  4.29515419  3.16236627  0.09439899 
          8           7 
 0.06293266  0.03146633 </code></pre>
</div>
</div>
<p>Características principales del grupo:</p>
<ul>
<li>Las semanas de gestación en las que se produjo la defunción van de 22 a 44. El 50% de las defunciones fueron abajo de la semana 38.</li>
<li>La edad promedio de la mujer era de 36 años. Siendo la edad mínima 29 y la máxima 57. Teniendo que el 75% de las mujeres tenian entre 29 y 39 años.</li>
<li>La cantidad de hijos tenidos para el grupo va de 1 a 32, siendo el promedio de 6. El 75% de las observaciones están por debajo de los 7 hijos tenidos.</li>
<li>La cantidad de hijos vivos en promedio es de 4. El 75% de las observaciones tienen menos de 6 hijos vivos.</li>
<li>En este grupo la mayoría de mujeres tienen 1 hijo en el parto y un 2.7% tienen 2.</li>
<li>En este grupo la mayoría de mujeres, un 53%, no tienen educación. Un 33% tienen educación primara.</li>
</ul>
<p>Con las caracteristicas mencionadas anteriormente podemos denotar a este grupo como “grupo de madres mayores con mayor cantidad de hijos tenidos con escolaridad mayormente nula”.</p>
</section>
</section>
</section>
<section id="resumen-del-analisis-exploratorio" class="level3">
<h3 class="anchored" data-anchor-id="resumen-del-analisis-exploratorio">Resumen del analisis exploratorio</h3>
<p>Luego de realizar el analisis exploratorio sobre los datos de las defunciones fetales en Guatemala desde el 2010 hasta el 2019, de forma general podemos concluir que: Guatemala es lastimosamente un pais donde la cantidad de defunciones fetales es muy alta, teniendo un promedio de 2,774 defunciones fetales por año. siendo que más del 50% de las defunciones fetales ocurren enntre la semana 36 a la 50 de gestación pero mayormente se dan en la semana 40 por lo que indica que los fetos ya habian llegado a desarrllarse bastante, esto ocurre en todas las regiones de nuestro pais y muy tristemente en todo tipo de mujeres. La mayoria de las defunciones fetales ocurren en mujeres de entre 20 y 30 años, aunque el 75% de las mujeres tienen menos de 28 años. A pesar de ello podemos encontrar niñas de tan solo 10 año que han tenido que enfrentar la muerte de su hijo. Normalmente las mujeres tienen 1 hijo en el parto pero existe un 6.6% de muejres que tienen 2. De las madres tambien se obtuvo que un 39%, tienen una educación primaria y un 26% tienen educación nula, pero la gran mayoria de las defunciones fetales ocurren en mujeres que no tienen educación.</p>
<p>Sobre datos un poco más especificos se pudo observar que existe relacion entre variables como el departamento de ocurrencia de la defuncion con la atencion medica que se recibe en este departamento, lo que nos indica que a menor antencion medica existe una mayor probabilidad de que la defuncion fetal ocurra. Por lo que se puede concluir que en Guatemala existe una gran desigualdad en cuanto a la atencion medica que se recibe en cada departamento y con este estudio se quiere detectar que departamentos son los que tienen una aistencia medica mas baja, para asi poder mejorarla y constribuir a la reduccion de la cantidad de defunciones fetales.</p>
<p>Por ultimo se pudo observar que existe una tendencia en la reducción de la cantidad de defunciones fetales a lo largo de los años, lo que nos da un poco de esperanza porque se puede visualizar un ciclo que se repite aproximadamente cada año y medio en donde la cantidad de estas reduce.</p>
</section>
<section id="referencias" class="level3">
<h3 class="anchored" data-anchor-id="referencias">Referencias</h3>
<ul>
<li><p>Kestler, E., &amp; Ambrosio, G. (2022). Nacido muerto en la comunidad y su relación con la morbilidad materna aguda y grave. Revista Médica (Colegio de Médicos Y Cirujanos de Guatemala), 161(2), 105–112. https://doi.org/10.36109/rmg.v161i2.484MSPAS. (2017). VI</p></li>
<li><p>Encuesta Nacional de Salud Materno Infantil (ENSMI) 2014-2015 Informe Final. https://www.ine.gob.gt/sistema/uploads/2021/04/27/20210427195413QDinUvuRa9GjopyXaTuNMXc3gd6Jq1Q1.pdf</p></li>
</ul>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>