<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.2.335">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Diego Franco, Daniel Gonzalez, Angel Carrera">

<title>Proyecto</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="Proyecto_modelos_files/libs/clipboard/clipboard.min.js"></script>
<script src="Proyecto_modelos_files/libs/quarto-html/quarto.js"></script>
<script src="Proyecto_modelos_files/libs/quarto-html/popper.min.js"></script>
<script src="Proyecto_modelos_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Proyecto_modelos_files/libs/quarto-html/anchor.min.js"></script>
<link href="Proyecto_modelos_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Proyecto_modelos_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Proyecto_modelos_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Proyecto_modelos_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Proyecto_modelos_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Proyecto</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Diego Franco, Daniel Gonzalez, Angel Carrera </p>
          </div>
  </div>
    
  
    
  </div>
  

</header>

<section id="defunciones-fetales-y-nacimientos-en-guatemala" class="level1">
<h1>Defunciones fetales y nacimientos en Guatemala</h1>
<section id="definición-de-variable-respuesta" class="level2">
<h2 class="anchored" data-anchor-id="definición-de-variable-respuesta">1. Definición de variable respuesta</h2>
<p>La variable por utilizar será <strong>TIPO</strong>, la cual indica si un parto terminó en una defunción fetal o en un nacimiento. Debido a que la investigación de este trabaja está orientada a crear una herramienta que permita ayudar a identificar partos potencialmente problemáticos, se decidió usar esta variable como la respuesta. Esto permitirá saber, dadas las condiciones de una mujer embarazada, si tiene algún riesgo.</p>
<p>Cabe mencionar que esta variable no existía dentro del dataset inicial, sino que a la hora de hacer la unión entre los conjuntos de datos de nacimientos y defunciones se indicó de qué conjunto de datos era proveniente cada observación.</p>
<section id="limpieza-de-datos" class="level3">
<h3 class="anchored" data-anchor-id="limpieza-de-datos">1.1 Limpieza de datos</h3>
</section>
<section id="análsis-de-na-y-limpieza" class="level3">
<h3 class="anchored" data-anchor-id="análsis-de-na-y-limpieza">Análsis de NA y limpieza</h3>
<p>Los datos tienen un encoding en el que se pone un número (como 99 o 999) para indicar que no se tiene información. Por lo tanto es necesario reemplazar estos números por NA.</p>
<div class="cell">

</div>
<p>Además, también se tienen muchas variables con valores numéricos pero que son cualitativas. Por lo tanto, se conviertieron en factores.</p>
<div class="cell">

</div>
</section>
</section>
<section id="eliminación-de-variables-no-significativas" class="level2">
<h2 class="anchored" data-anchor-id="eliminación-de-variables-no-significativas">Eliminación de variables no significativas</h2>
<p>Hay ciertos años que no tienen todas las variables que años mas recientes tienen entonces para tener una mayor covertura de años se eliminan las variables que no tienen datos en todos los años.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">na.omit</span>(datos)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>datos <span class="ot">&lt;-</span> <span class="fu">select</span>(datos, <span class="sc">-</span>SEMGES, <span class="sc">-</span>MUPREG, <span class="sc">-</span>MUPOCU, <span class="sc">-</span>DEPOCU, <span class="sc">-</span>MUPREM, <span class="sc">-</span>DEPREG, <span class="sc">-</span>DEPREM, <span class="sc">-</span>TOHITE, <span class="sc">-</span>AÑOREG)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># colnames(datos)[2] &lt;- 'ANOREG'</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="obtención-de-datos-de-entrenamiento-y-prueba" class="level2">
<h2 class="anchored" data-anchor-id="obtención-de-datos-de-entrenamiento-y-prueba">2. Obtención de datos de entrenamiento y prueba</h2>
<section id="creación-de-train-y-test" class="level3">
<h3 class="anchored" data-anchor-id="creación-de-train-y-test">Creación de train y test</h3>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>porcentaje <span class="ot">&lt;-</span> <span class="fl">0.7</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a>corte <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(datos), <span class="fu">nrow</span>(datos) <span class="sc">*</span> porcentaje)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> datos[corte, ]</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a>test <span class="ot">&lt;-</span> datos[<span class="sc">-</span>corte, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Para obtener los conjuntos de entrenamiento y prueba, se utilizó un método de división aleatoria.</p>
<p>En este caso, se dividió el conjunto de datos en un 70% para entrenamiento y un 30% para pruebas. Esto significa que el 70% de las muestras se utilizaron para entrenar el modelo y el 30% restante se reservaron para evaluar el rendimiento del modelo en datos no vistos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>num_vivos <span class="ot">&lt;-</span> <span class="fu">sum</span>(train<span class="sc">$</span>TIPO <span class="sc">==</span> <span class="st">'vivo'</span>)</span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>porcentaje_vivos <span class="ot">&lt;-</span> (num_vivos <span class="sc">/</span> <span class="fu">nrow</span>(train)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>porcentaje_vivos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 67.17339</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span> <span class="sc">-</span> porcentaje_vivos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 32.82661</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a>num_vivos <span class="ot">&lt;-</span> <span class="fu">sum</span>(test<span class="sc">$</span>TIPO <span class="sc">==</span> <span class="st">'vivo'</span>)</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a>porcentaje_vivos <span class="ot">&lt;-</span> (num_vivos <span class="sc">/</span> <span class="fu">nrow</span>(test)) <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>porcentaje_vivos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 67.64052</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="dv">100</span> <span class="sc">-</span> porcentaje_vivos</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 32.35948</code></pre>
</div>
</div>
<p>Al realizar la limpieza de NAs, sucede que se desbalancea el dataset, quedando más registros vivos. Tanto en train como en test se tiene un 67% de datos de embarazos exitosos y un 33% de datos de defunciones fetales. No se tiene un desbalance tan drástico, pero se buscará usar una métrica como F1, aparte de accuracy, de forma que se penalice este desbalance y se puedan evaluar de una mejor manera los modelos.</p>
</section>
</section>
<section id="transformaciones-realizadas-para-poder-usar-los-modelos" class="level2">
<h2 class="anchored" data-anchor-id="transformaciones-realizadas-para-poder-usar-los-modelos">3. Transformaciones realizadas para poder usar los modelos</h2>
<p>Para poder utilizar los modelos elegidos con aterioridad, se realizaron diversas transformaciones para asegurar la calidad y la adecuación de los datos. En primer lugar, se llevó a cabo un análisis exhaustivo de los valores faltantes (NA) presentes en el conjunto de datos. Se identificaron las variables con valores faltantes y se decidió hacer la eliminación de las observaciones correspondientes. Esto permitió asegurar que los datos utilizados estuvieran completos y representativos.</p>
<p>Además, se llevó a cabo una evaluación de la relevancia y significancia de las variables presentes en el conjunto de datos. Mediante técnicas de análisis exploratorio, se identificaron las variables que tenían una contribución limitada o nula para los objetivos del análisis. Estas variables no significativas fueron eliminadas del conjunto de datos, simplificando así su estructura y reduciendo la complejidad.</p>
<section id="datos-necesarios-para-svm-y-xgboost" class="level3">
<h3 class="anchored" data-anchor-id="datos-necesarios-para-svm-y-xgboost">3.1 Datos necesarios para SVM y XGBoost</h3>
<p>Para la SVM y el XGBoost se necesitaran los datos codificados, por lo que se procede a codificar las variables cualitativass en cuantitativas y para esto se utiliza el método de codificación one-hot. Para la variable objetivo se utiliza la codificación de 1 para un embarazo fallido y 0 para un embarazo exitoso.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a>data <span class="ot">&lt;-</span> datos</span>
<span id="cb11-3"><a href="#cb11-3" aria-hidden="true" tabindex="-1"></a>cualitativas2 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">'MESREG'</span>, <span class="st">'AÑOREG'</span>, <span class="st">'SEXO'</span>, <span class="st">'DIAOCU'</span>, <span class="st">'MESOCU'</span>, <span class="st">'TIPAR'</span>, <span class="st">'ESCIVM'</span>, <span class="st">'ESCOLAM'</span>, <span class="st">'ASISREC'</span>, <span class="st">'SITIOOCU'</span>)</span>
<span id="cb11-4"><a href="#cb11-4" aria-hidden="true" tabindex="-1"></a>cualitativas2_indices <span class="ot">&lt;-</span> <span class="fu">which</span>(<span class="fu">colnames</span>(data) <span class="sc">%in%</span> cualitativas2)</span>
<span id="cb11-5"><a href="#cb11-5" aria-hidden="true" tabindex="-1"></a>data<span class="sc">$</span>TIPO <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(data<span class="sc">$</span>TIPO <span class="sc">==</span> <span class="st">"muerto"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb11-6"><a href="#cb11-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-7"><a href="#cb11-7" aria-hidden="true" tabindex="-1"></a>encoding_model <span class="ot">&lt;-</span> <span class="fu">dummyVars</span>(<span class="sc">~</span>., <span class="at">data =</span> data[, cualitativas2_indices], <span class="at">fullRank =</span> <span class="cn">TRUE</span>)</span>
<span id="cb11-8"><a href="#cb11-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-9"><a href="#cb11-9" aria-hidden="true" tabindex="-1"></a>encoded_data <span class="ot">&lt;-</span> <span class="fu">predict</span>(encoding_model, <span class="at">newdata =</span> data[, cualitativas2_indices])</span>
<span id="cb11-10"><a href="#cb11-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-11"><a href="#cb11-11" aria-hidden="true" tabindex="-1"></a>final_data <span class="ot">&lt;-</span> <span class="fu">cbind</span>(data[, <span class="sc">!</span>cualitativas2_indices], encoded_data)</span>
<span id="cb11-12"><a href="#cb11-12" aria-hidden="true" tabindex="-1"></a>final_data<span class="sc">$</span>TIPO <span class="ot">&lt;-</span> data<span class="sc">$</span>TIPO</span>
<span id="cb11-13"><a href="#cb11-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-14"><a href="#cb11-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-15"><a href="#cb11-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-16"><a href="#cb11-16" aria-hidden="true" tabindex="-1"></a>porcentaje <span class="ot">&lt;-</span> <span class="fl">0.7</span></span>
<span id="cb11-17"><a href="#cb11-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb11-18"><a href="#cb11-18" aria-hidden="true" tabindex="-1"></a>corte <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(final_data), <span class="fu">nrow</span>(final_data) <span class="sc">*</span> porcentaje)</span>
<span id="cb11-19"><a href="#cb11-19" aria-hidden="true" tabindex="-1"></a>train1 <span class="ot">&lt;-</span> final_data[corte, ]</span>
<span id="cb11-20"><a href="#cb11-20" aria-hidden="true" tabindex="-1"></a>test1 <span class="ot">&lt;-</span> final_data[<span class="sc">-</span>corte, ]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
<section id="creación-de-modelos" class="level2">
<h2 class="anchored" data-anchor-id="creación-de-modelos">4. Creación de modelos</h2>
<section id="svm" class="level3">
<h3 class="anchored" data-anchor-id="svm">4.1 SVM</h3>
<section id="parameter-tuning" class="level4">
<h4 class="anchored" data-anchor-id="parameter-tuning">4.1.1 Parameter tuning</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define los rangos de los parámetros que deseas ajustar</span></span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a><span class="co"># tune.grid &lt;- expand.grid(.cost = 10^(-1:2),   # Por ejemplo, costos de 0.1, 1, 10, 100</span></span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a><span class="co">#                          .gamma = c(0.5, 1))  # Por ejemplo, gammas de 0.5, 1</span></span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a><span class="co"># # Realiza el ajuste</span></span>
<span id="cb12-6"><a href="#cb12-6" aria-hidden="true" tabindex="-1"></a><span class="co"># tune.out &lt;- tune(svm, TIPO~., data = train, kernel = "linear",</span></span>
<span id="cb12-7"><a href="#cb12-7" aria-hidden="true" tabindex="-1"></a><span class="co">#                  ranges = tune.grid)</span></span>
<span id="cb12-8"><a href="#cb12-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-9"><a href="#cb12-9" aria-hidden="true" tabindex="-1"></a><span class="co"># # Imprime los resultados del ajuste</span></span>
<span id="cb12-10"><a href="#cb12-10" aria-hidden="true" tabindex="-1"></a><span class="co"># print(tune.out)</span></span>
<span id="cb12-11"><a href="#cb12-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-12"><a href="#cb12-12" aria-hidden="true" tabindex="-1"></a><span class="co"># # Obtén el mejor modelo</span></span>
<span id="cb12-13"><a href="#cb12-13" aria-hidden="true" tabindex="-1"></a><span class="co"># best.model &lt;- tune.out$best.model</span></span>
<span id="cb12-14"><a href="#cb12-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb12-15"><a href="#cb12-15" aria-hidden="true" tabindex="-1"></a><span class="co"># # Imprime el mejor modelo</span></span>
<span id="cb12-16"><a href="#cb12-16" aria-hidden="true" tabindex="-1"></a><span class="co"># print(best.model)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Se obtuvo del parameter tuning que el mejor kernel es el lineal, con costo de 10 y gamma de 0.1.</p>
</section>
<section id="curva-de-aprendizaje" class="level4">
<h4 class="anchored" data-anchor-id="curva-de-aprendizaje">4.1.2 Curva de aprendizaje</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Dividir los datos en conjuntos de entrenamiento y prueba</span></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># modeloSVM &lt;- svm(TIPO~., data = train, kernel = "linear", cost = 10, gamma = 0.1)</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>modeloSVM <span class="ot">&lt;-</span> <span class="fu">readRDS</span>(<span class="st">"./modelos/modeloSVM.rds"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a>folds <span class="ot">&lt;-</span> <span class="fu">createFolds</span>(train<span class="sc">$</span>TIPO, <span class="at">k =</span> <span class="dv">25</span>, <span class="at">list =</span> <span class="cn">TRUE</span>, <span class="at">returnTrain =</span> <span class="cn">TRUE</span>)</span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>    rmse_train <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="at">length =</span> <span class="fu">length</span>(folds))</span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>    rmse_test <span class="ot">&lt;-</span> <span class="fu">vector</span>(<span class="at">length =</span> <span class="fu">length</span>(folds))</span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-6"><a href="#cb14-6" aria-hidden="true" tabindex="-1"></a>   </span>
<span id="cb14-7"><a href="#cb14-7" aria-hidden="true" tabindex="-1"></a>    <span class="cf">for</span> (i <span class="cf">in</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(folds)){</span>
<span id="cb14-8"><a href="#cb14-8" aria-hidden="true" tabindex="-1"></a>        train_data <span class="ot">&lt;-</span> train[folds[[i]],]</span>
<span id="cb14-9"><a href="#cb14-9" aria-hidden="true" tabindex="-1"></a>        test_data <span class="ot">&lt;-</span> train[<span class="sc">-</span>folds[[i]],]</span>
<span id="cb14-10"><a href="#cb14-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-11"><a href="#cb14-11" aria-hidden="true" tabindex="-1"></a>        pred_train <span class="ot">&lt;-</span> <span class="fu">predict</span>(modeloSVM, <span class="at">newdata =</span> train_data )</span>
<span id="cb14-12"><a href="#cb14-12" aria-hidden="true" tabindex="-1"></a>        pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(modeloSVM, <span class="at">newdata =</span> test_data)</span>
<span id="cb14-13"><a href="#cb14-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-14"><a href="#cb14-14" aria-hidden="true" tabindex="-1"></a>        rmse_train[i] <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred_train, train_data<span class="sc">$</span>TIPO)<span class="sc">$</span>overall[<span class="st">"Accuracy"</span>]</span>
<span id="cb14-15"><a href="#cb14-15" aria-hidden="true" tabindex="-1"></a>        rmse_test[i] <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(pred, test_data<span class="sc">$</span>TIPO)<span class="sc">$</span>overall[<span class="st">"Accuracy"</span>]</span>
<span id="cb14-16"><a href="#cb14-16" aria-hidden="true" tabindex="-1"></a>    }</span>
<span id="cb14-17"><a href="#cb14-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-18"><a href="#cb14-18" aria-hidden="true" tabindex="-1"></a>    rmse_df <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb14-19"><a href="#cb14-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">Fold =</span> <span class="dv">1</span><span class="sc">:</span><span class="fu">length</span>(folds),</span>
<span id="cb14-20"><a href="#cb14-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">RMSE_Train =</span> rmse_train,</span>
<span id="cb14-21"><a href="#cb14-21" aria-hidden="true" tabindex="-1"></a>  <span class="at">RMSE_Test =</span> rmse_test</span>
<span id="cb14-22"><a href="#cb14-22" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb14-23"><a href="#cb14-23" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb14-24"><a href="#cb14-24" aria-hidden="true" tabindex="-1"></a><span class="co"># Crear el gráfico de línea</span></span>
<span id="cb14-25"><a href="#cb14-25" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(rmse_df, <span class="fu">aes</span>(<span class="at">x =</span> Fold)) <span class="sc">+</span></span>
<span id="cb14-26"><a href="#cb14-26" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> RMSE_Train, <span class="at">color =</span> <span class="st">"Conjunto de Entrenamiento"</span>)) <span class="sc">+</span></span>
<span id="cb14-27"><a href="#cb14-27" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y =</span> RMSE_Test, <span class="at">color =</span> <span class="st">"Conjunto de Prueba"</span>)) <span class="sc">+</span></span>
<span id="cb14-28"><a href="#cb14-28" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Valores de RMSE en la validación cruzada"</span>,</span>
<span id="cb14-29"><a href="#cb14-29" aria-hidden="true" tabindex="-1"></a>       <span class="at">x =</span> <span class="st">"Fold"</span>,</span>
<span id="cb14-30"><a href="#cb14-30" aria-hidden="true" tabindex="-1"></a>       <span class="at">y =</span> <span class="st">"RMSE"</span>) <span class="sc">+</span></span>
<span id="cb14-31"><a href="#cb14-31" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Conjunto de Entrenamiento"</span> <span class="ot">=</span> <span class="st">"blue"</span>, <span class="st">"Conjunto de Prueba"</span> <span class="ot">=</span> <span class="st">"red"</span>)) <span class="sc">+</span></span>
<span id="cb14-32"><a href="#cb14-32" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Proyecto_modelos_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Se puede observar un gráfico en donde los datos no son representativos, esto porque las líneas se cruzan entre sí y no hay una relación clara entre los datos de entrenamiento y prueba.</p>
</section>
<section id="predicciones" class="level4">
<h4 class="anchored" data-anchor-id="predicciones">4.1.3 Predicciones</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(modeloSVM)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
svm(formula = TIPO ~ ., data = train, kernel = "linear", cost = 10, 
    gamma = 0.1)


Parameters:
   SVM-Type:  C-classification 
 SVM-Kernel:  linear 
       cost:  10 

Number of Support Vectors:  15031</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>svmpredicciones <span class="ot">&lt;-</span> <span class="fu">predict</span>(modeloSVM, test)</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>svmConfusionMatrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(svmpredicciones, test<span class="sc">$</span>TIPO)</span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(svmConfusionMatrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction muerto vivo
    muerto   3932  737
    vivo        0 7482
                                         
               Accuracy : 0.9393         
                 95% CI : (0.935, 0.9435)
    No Information Rate : 0.6764         
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16      
                                         
                  Kappa : 0.8679         
                                         
 Mcnemar's Test P-Value : &lt; 2.2e-16      
                                         
            Sensitivity : 1.0000         
            Specificity : 0.9103         
         Pos Pred Value : 0.8422         
         Neg Pred Value : 1.0000         
             Prevalence : 0.3236         
         Detection Rate : 0.3236         
   Detection Prevalence : 0.3842         
      Balanced Accuracy : 0.9552         
                                         
       'Positive' Class : muerto         
                                         </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a>f1_score <span class="ot">&lt;-</span> svmConfusionMatrix<span class="sc">$</span>byClass[<span class="st">"F1"</span>]</span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>f1_score</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       F1 
0.9143123 </code></pre>
</div>
</div>
</section>
</section>
<section id="red-neuronal" class="level3">
<h3 class="anchored" data-anchor-id="red-neuronal">4.2 Red neuronal</h3>
<section id="parameter-tuning-red-neuronal" class="level4">
<h4 class="anchored" data-anchor-id="parameter-tuning-red-neuronal">4.2.1 Parameter tuning red neuronal</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>param_grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">size =</span> <span class="fu">c</span>(<span class="dv">5</span>, <span class="dv">10</span>, <span class="dv">15</span>), <span class="at">decay =</span> <span class="fu">c</span>(<span class="fl">0.1</span>, <span class="fl">0.01</span>, <span class="fl">0.001</span>))</span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-3"><a href="#cb21-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb21-4"><a href="#cb21-4" aria-hidden="true" tabindex="-1"></a>ctrl <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">5</span>)  <span class="co"># Cross-validation control</span></span>
<span id="cb21-5"><a href="#cb21-5" aria-hidden="true" tabindex="-1"></a>tuned_model <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">train</span>(TIPO <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"nnet"</span>,</span>
<span id="cb21-6"><a href="#cb21-6" aria-hidden="true" tabindex="-1"></a>                     <span class="at">tuneGrid =</span> param_grid, <span class="at">trControl =</span> ctrl, <span class="at">metric =</span> <span class="st">"Accuracy"</span>, <span class="at">trace=</span><span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: model fit failed for Fold1: size=15, decay=0.100 Error in nnet.default(x, y, w, entropy = TRUE, ...) : 
  too many (1186) weights</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: model fit failed for Fold1: size=15, decay=0.010 Error in nnet.default(x, y, w, entropy = TRUE, ...) : 
  too many (1186) weights</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: model fit failed for Fold1: size=15, decay=0.001 Error in nnet.default(x, y, w, entropy = TRUE, ...) : 
  too many (1186) weights</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: model fit failed for Fold2: size=15, decay=0.100 Error in nnet.default(x, y, w, entropy = TRUE, ...) : 
  too many (1186) weights</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: model fit failed for Fold2: size=15, decay=0.010 Error in nnet.default(x, y, w, entropy = TRUE, ...) : 
  too many (1186) weights</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: model fit failed for Fold2: size=15, decay=0.001 Error in nnet.default(x, y, w, entropy = TRUE, ...) : 
  too many (1186) weights</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: model fit failed for Fold3: size=15, decay=0.100 Error in nnet.default(x, y, w, entropy = TRUE, ...) : 
  too many (1186) weights</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: model fit failed for Fold3: size=15, decay=0.010 Error in nnet.default(x, y, w, entropy = TRUE, ...) : 
  too many (1186) weights</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: model fit failed for Fold3: size=15, decay=0.001 Error in nnet.default(x, y, w, entropy = TRUE, ...) : 
  too many (1186) weights</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: model fit failed for Fold4: size=15, decay=0.100 Error in nnet.default(x, y, w, entropy = TRUE, ...) : 
  too many (1186) weights</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: model fit failed for Fold4: size=15, decay=0.010 Error in nnet.default(x, y, w, entropy = TRUE, ...) : 
  too many (1186) weights</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: model fit failed for Fold4: size=15, decay=0.001 Error in nnet.default(x, y, w, entropy = TRUE, ...) : 
  too many (1186) weights</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: model fit failed for Fold5: size=15, decay=0.100 Error in nnet.default(x, y, w, entropy = TRUE, ...) : 
  too many (1186) weights</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: model fit failed for Fold5: size=15, decay=0.010 Error in nnet.default(x, y, w, entropy = TRUE, ...) : 
  too many (1186) weights</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: model fit failed for Fold5: size=15, decay=0.001 Error in nnet.default(x, y, w, entropy = TRUE, ...) : 
  too many (1186) weights</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in nominalTrainWorkflow(x = x, y = y, wts = weights, info = trainInfo, :
There were missing values in resampled performance measures.</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in train.default(x, y, weights = w, ...): missing values found in
aggregated results</code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>best_size <span class="ot">&lt;-</span> tuned_model<span class="sc">$</span>bestTune<span class="sc">$</span>size</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>best_decay <span class="ot">&lt;-</span> tuned_model<span class="sc">$</span>bestTune<span class="sc">$</span>decay</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(best_size)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 10</code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(best_decay)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1</code></pre>
</div>
</div>
<p>El tuneo de parámetros se realizó con una sola capa. Se usaron topologías de 5, 10 y 15 neuronas. Aparte, se evaluó un decay de 0.1, 0.01 y 0.001. Luego de ejecutar el procedimiento, se obtuvo que el mejor modelo usa 10 neuronas y un decay de 0.01. Sin embargo, este modelo dió overfitting. Cuando se usó 0.0001 de decay y 5 neuronas, no hubo overfitting.</p>
</section>
<section id="creación-de-curva-de-aprendizaje" class="level4">
<h4 class="anchored" data-anchor-id="creación-de-curva-de-aprendizaje">4.2.3 Creación de curva de aprendizaje</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a>datos.task <span class="ot">=</span> <span class="fu">makeClassifTask</span>(<span class="at">data =</span> train, <span class="at">target =</span> <span class="st">"TIPO"</span>)</span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>rin2 <span class="ot">=</span> <span class="fu">makeResampleDesc</span>(<span class="at">method =</span> <span class="st">"CV"</span>, <span class="at">iters =</span> <span class="dv">10</span>, <span class="at">predict =</span> <span class="st">"both"</span>)</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>lrn <span class="ot">=</span> <span class="fu">makeLearner</span>(<span class="st">"classif.nnet"</span>, <span class="at">size =</span> <span class="dv">5</span>, <span class="at">decay =</span> <span class="fl">0.0001</span>, <span class="at">maxit =</span> <span class="dv">1000</span>, <span class="at">trace =</span> <span class="cn">FALSE</span>)</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>lc2 <span class="ot">=</span> <span class="fu">generateLearningCurveData</span>(<span class="at">learners =</span> lrn, <span class="at">task =</span> datos.task,</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">percs =</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>),</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">measures =</span> <span class="fu">list</span>(ber, <span class="fu">setAggregation</span>(ber, train.mean)), <span class="at">resampling =</span> rin2,</span>
<span id="cb43-7"><a href="#cb43-7" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">show.info =</span> <span class="cn">FALSE</span>)</span>
<span id="cb43-8"><a href="#cb43-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plotLearningCurve</span>(lc2, <span class="at">facet =</span> <span class="st">"learner"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Proyecto_modelos_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Como se puede observar en la gráfica, la curva de test y la curva de train, tienen un comportamiento muy similar. A pesar de que hay diversos aumentos y disminuciones en las curvas, estas son muy cercanas. En conclusión, estas convergen, por lo que no se da overfitting.</p>
</section>
<section id="predicción-y-datos-de-validación" class="level4">
<h4 class="anchored" data-anchor-id="predicción-y-datos-de-validación">4.2.4 Predicción y datos de validación</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a>porcentaje <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>nnet_model <span class="ot">&lt;-</span> <span class="fu">nnet</span>(TIPO <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">size=</span><span class="dv">5</span>, <span class="at">decay=</span><span class="fl">0.0001</span>, <span class="at">softmax =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  396
initial  value 20027.835797 
iter  10 value 14212.021425
iter  20 value 11916.678532
iter  30 value 8960.048465
iter  40 value 6371.468702
iter  50 value 5660.518349
iter  60 value 4467.856356
iter  70 value 4365.258640
iter  80 value 4267.823170
iter  90 value 4238.323861
iter 100 value 4205.221446
final  value 4205.221446 
stopped after 100 iterations</code></pre>
</div>
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions on the test set</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a>predictions1 <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">predict</span>(nnet_model, <span class="at">newdata =</span> test, <span class="at">type =</span> <span class="st">"class"</span>))</span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a>confusion_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(<span class="at">reference =</span> test<span class="sc">$</span>TIPO, <span class="at">data =</span> predictions1)</span>
<span id="cb46-5"><a href="#cb46-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-6"><a href="#cb46-6" aria-hidden="true" tabindex="-1"></a>confusion_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction muerto vivo
    muerto   3891  608
    vivo       41 7611
                                          
               Accuracy : 0.9466          
                 95% CI : (0.9424, 0.9505)
    No Information Rate : 0.6764          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.8824          
                                          
 Mcnemar's Test P-Value : &lt; 2.2e-16       
                                          
            Sensitivity : 0.9896          
            Specificity : 0.9260          
         Pos Pred Value : 0.8649          
         Neg Pred Value : 0.9946          
             Prevalence : 0.3236          
         Detection Rate : 0.3202          
   Detection Prevalence : 0.3703          
      Balanced Accuracy : 0.9578          
                                          
       'Positive' Class : muerto          
                                          </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>porcentaje <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a>corte <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(test), <span class="fu">nrow</span>(test) <span class="sc">*</span> porcentaje)</span>
<span id="cb48-3"><a href="#cb48-3" aria-hidden="true" tabindex="-1"></a>test2 <span class="ot">&lt;-</span> test[corte, ]</span>
<span id="cb48-4"><a href="#cb48-4" aria-hidden="true" tabindex="-1"></a>validation2 <span class="ot">&lt;-</span> test[<span class="sc">-</span>corte,]</span>
<span id="cb48-5"><a href="#cb48-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb48-6"><a href="#cb48-6" aria-hidden="true" tabindex="-1"></a>nnet_model <span class="ot">&lt;-</span> <span class="fu">nnet</span>(TIPO <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">size=</span><span class="dv">5</span>, <span class="at">decay=</span><span class="fl">0.0001</span>, <span class="at">softmax =</span> <span class="cn">FALSE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># weights:  396
initial  value 18721.619632 
iter  10 value 16561.437322
iter  20 value 8883.437078
iter  30 value 4431.602722
iter  40 value 4313.615488
iter  50 value 4237.423773
iter  60 value 4200.290872
iter  70 value 4191.203609
iter  80 value 4188.012570
iter  90 value 4183.254355
iter 100 value 4181.230318
final  value 4181.230318 
stopped after 100 iterations</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions on the test set</span></span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>predictions1 <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">predict</span>(nnet_model, <span class="at">newdata =</span> test2, <span class="at">type =</span> <span class="st">"class"</span>))</span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>predictions2 <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">predict</span>(nnet_model, <span class="at">newdata =</span> validation2, <span class="at">type =</span> <span class="st">"class"</span>))</span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>confusion_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(<span class="at">reference =</span> test2<span class="sc">$</span>TIPO, <span class="at">data =</span> predictions1)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a>confusion_matrix2 <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(<span class="at">reference =</span> validation2<span class="sc">$</span>TIPO, <span class="at">data =</span> predictions2)</span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>confusion_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction muerto vivo
    muerto   1973  384
    vivo        0 3718
                                          
               Accuracy : 0.9368          
                 95% CI : (0.9304, 0.9428)
    No Information Rate : 0.6752          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.8628          
                                          
 Mcnemar's Test P-Value : &lt; 2.2e-16       
                                          
            Sensitivity : 1.0000          
            Specificity : 0.9064          
         Pos Pred Value : 0.8371          
         Neg Pred Value : 1.0000          
             Prevalence : 0.3248          
         Detection Rate : 0.3248          
   Detection Prevalence : 0.3880          
      Balanced Accuracy : 0.9532          
                                          
       'Positive' Class : muerto          
                                          </code></pre>
</div>
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a>confusion_matrix2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction muerto vivo
    muerto   1959  359
    vivo        0 3758
                                          
               Accuracy : 0.9409          
                 95% CI : (0.9347, 0.9467)
    No Information Rate : 0.6776          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.871           
                                          
 Mcnemar's Test P-Value : &lt; 2.2e-16       
                                          
            Sensitivity : 1.0000          
            Specificity : 0.9128          
         Pos Pred Value : 0.8451          
         Neg Pred Value : 1.0000          
             Prevalence : 0.3224          
         Detection Rate : 0.3224          
   Detection Prevalence : 0.3815          
      Balanced Accuracy : 0.9564          
                                          
       'Positive' Class : muerto          
                                          </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a>f1_score <span class="ot">&lt;-</span> confusion_matrix<span class="sc">$</span>byClass[<span class="st">"F1"</span>]</span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>f1_score</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       F1 
0.9113164 </code></pre>
</div>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a>f1_score <span class="ot">&lt;-</span> confusion_matrix2<span class="sc">$</span>byClass[<span class="st">"F1"</span>]</span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>f1_score</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       F1 
0.9160627 </code></pre>
</div>
</div>
<p>Se usó un set de datos de prueba y uno validación para poder evaluar el overfitting. Las métricas entre el set de validación y el de prueba no difieren significativamente, por lo que se puede confirmar que no hay overfitting.</p>
</section>
</section>
<section id="xgboost" class="level3">
<h3 class="anchored" data-anchor-id="xgboost">4.3 XGBoost</h3>
<section id="parameter-tunning" class="level4">
<h4 class="anchored" data-anchor-id="parameter-tunning">4.3.1 Parameter tunning</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>TIPO_temp <span class="ot">&lt;-</span> train1<span class="sc">$</span>TIPO</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>train1<span class="sc">$</span>TIPO <span class="ot">&lt;-</span> train<span class="sc">$</span>TIPO</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>task <span class="ot">&lt;-</span> <span class="fu">makeClassifTask</span>(<span class="at">data =</span> train1, <span class="at">target =</span> <span class="st">"TIPO"</span>)</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>param_grid <span class="ot">&lt;-</span> <span class="fu">makeParamSet</span>(</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">makeDiscreteParam</span>(<span class="st">"nrounds"</span>, <span class="at">values =</span> <span class="fu">seq</span>(<span class="dv">100</span>, <span class="dv">500</span>, <span class="at">by =</span> <span class="dv">20</span>)),</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">makeIntegerParam</span>(<span class="st">"max_depth"</span>, <span class="at">lower =</span> <span class="dv">3</span>, <span class="at">upper =</span> <span class="dv">10</span>),</span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">makeNumericParam</span>(<span class="st">"eta"</span>, <span class="at">lower =</span> <span class="fl">0.01</span>, <span class="at">upper =</span> <span class="fl">0.3</span>)</span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>control_tune <span class="ot">&lt;-</span> <span class="fu">makeTuneControlRandom</span>(<span class="at">maxit =</span> <span class="dv">30</span>)</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>resampling <span class="ot">&lt;-</span> <span class="fu">makeResampleDesc</span>(<span class="st">"CV"</span>, <span class="at">iters =</span> <span class="dv">5</span>)</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>measure <span class="ot">&lt;-</span> acc</span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a>tuned_model <span class="ot">&lt;-</span> <span class="fu">tuneParams</span>(</span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a>  <span class="at">learner =</span> <span class="st">"classif.xgboost"</span>,  <span class="co"># For classification, use "classif.xgboost"; for regression, use "regr.xgboost"</span></span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a>  <span class="at">task =</span> task,</span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a>  <span class="at">resampling =</span> resampling,</span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a>  <span class="at">measures =</span> measure,</span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">par.set =</span> param_grid,</span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a>  <span class="at">control =</span> control_tune,</span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a>  <span class="at">show.info =</span> <span class="cn">TRUE</span></span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune] Started tuning learner classif.xgboost for parameter set:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>              Type len Def                                   Constr Req Tunable
nrounds   discrete   -   - 100,120,140,160,180,200,220,240,260,2...   -    TRUE
max_depth  integer   -   -                                  3 to 10   -    TRUE
eta        numeric   -   -                              0.01 to 0.3   -    TRUE
          Trafo
nrounds       -
max_depth     -
eta           -</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>With control class: TuneControlRandom</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Imputation value: -0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 1: nrounds=180; max_depth=5; eta=0.125</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 1: acc.test.mean=0.7905615; time: 0.2 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 2: nrounds=340; max_depth=6; eta=0.104</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 2: acc.test.mean=0.7907379; time: 0.4 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 3: nrounds=320; max_depth=6; eta=0.27</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 3: acc.test.mean=0.7818495; time: 0.4 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 4: nrounds=140; max_depth=6; eta=0.273</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 4: acc.test.mean=0.7909143; time: 0.2 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 5: nrounds=280; max_depth=6; eta=0.296</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 5: acc.test.mean=0.7839658; time: 0.3 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 6: nrounds=260; max_depth=7; eta=0.256</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 6: acc.test.mean=0.7815322; time: 0.4 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 7: nrounds=380; max_depth=3; eta=0.165</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 7: acc.test.mean=0.7889744; time: 0.2 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 8: nrounds=240; max_depth=6; eta=0.137</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 8: acc.test.mean=0.7906674; time: 0.3 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 9: nrounds=100; max_depth=4; eta=0.0814</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 9: acc.test.mean=0.7387836; time: 0.1 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 10: nrounds=200; max_depth=3; eta=0.0278</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 10: acc.test.mean=0.7050292; time: 0.1 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 11: nrounds=420; max_depth=3; eta=0.0885</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 11: acc.test.mean=0.7800859; time: 0.3 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 12: nrounds=120; max_depth=4; eta=0.225</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 12: acc.test.mean=0.7880574; time: 0.1 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 13: nrounds=220; max_depth=10; eta=0.16</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 13: acc.test.mean=0.7778287; time: 0.5 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 14: nrounds=480; max_depth=7; eta=0.123</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 14: acc.test.mean=0.7845301; time: 0.7 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 15: nrounds=500; max_depth=4; eta=0.151</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 15: acc.test.mean=0.7945118; time: 0.4 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 16: nrounds=300; max_depth=5; eta=0.199</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 16: acc.test.mean=0.7915844; time: 0.3 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 17: nrounds=120; max_depth=6; eta=0.154</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 17: acc.test.mean=0.7883395; time: 0.1 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 18: nrounds=200; max_depth=5; eta=0.19</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 18: acc.test.mean=0.7933127; time: 0.2 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 19: nrounds=220; max_depth=3; eta=0.0925</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 19: acc.test.mean=0.7603697; time: 0.1 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 20: nrounds=120; max_depth=8; eta=0.0218</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 20: acc.test.mean=0.7121186; time: 0.2 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 21: nrounds=340; max_depth=4; eta=0.0138</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 21: acc.test.mean=0.7073923; time: 0.3 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 22: nrounds=300; max_depth=3; eta=0.218</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 22: acc.test.mean=0.7916902; time: 0.2 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 23: nrounds=320; max_depth=6; eta=0.0848</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 23: acc.test.mean=0.7915492; time: 0.4 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 24: nrounds=160; max_depth=10; eta=0.175</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 24: acc.test.mean=0.7823434; time: 0.4 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 25: nrounds=260; max_depth=7; eta=0.0852</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 25: acc.test.mean=0.7887275; time: 0.4 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 26: nrounds=480; max_depth=10; eta=0.294</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 26: acc.test.mean=0.7595231; time: 1.0 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 27: nrounds=320; max_depth=8; eta=0.297</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 27: acc.test.mean=0.7727144; time: 0.5 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 28: nrounds=380; max_depth=6; eta=0.206</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 28: acc.test.mean=0.7838953; time: 0.5 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 29: nrounds=280; max_depth=9; eta=0.103</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 29: acc.test.mean=0.7841421; time: 0.6 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 30: nrounds=240; max_depth=10; eta=0.292</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 30: acc.test.mean=0.7694343; time: 0.5 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune] Result: nrounds=500; max_depth=4; eta=0.151 : acc.test.mean=0.7945118</code></pre>
</div>
<div class="sourceCode cell-code" id="cb124"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb124-1"><a href="#cb124-1" aria-hidden="true" tabindex="-1"></a>best_params <span class="ot">&lt;-</span> tuned_model<span class="sc">$</span>x</span>
<span id="cb124-2"><a href="#cb124-2" aria-hidden="true" tabindex="-1"></a>best_params</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$nrounds
[1] 500

$max_depth
[1] 4

$eta
[1] 0.1510747</code></pre>
</div>
</div>
<p>Despues de realizar el parameter tunning se obtuvo que los mejores parametros son: nrounds = 500, max_depth = 4, eta = 0.2254931. Esto se debe a que se obtuvo el mejor accuracy con estos parametros.</p>
</section>
<section id="curva-de-aprendizaje-1" class="level4">
<h4 class="anchored" data-anchor-id="curva-de-aprendizaje-1">4.3.2 Curva de aprendizaje</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb126"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb126-1"><a href="#cb126-1" aria-hidden="true" tabindex="-1"></a>train1<span class="sc">$</span>TIPO <span class="ot">&lt;-</span> train<span class="sc">$</span>TIPO</span>
<span id="cb126-2"><a href="#cb126-2" aria-hidden="true" tabindex="-1"></a>datos.task <span class="ot">&lt;-</span> <span class="fu">makeClassifTask</span>(<span class="at">data =</span> train1, <span class="at">target =</span> <span class="st">"TIPO"</span>)</span>
<span id="cb126-3"><a href="#cb126-3" aria-hidden="true" tabindex="-1"></a>rin2 <span class="ot">&lt;-</span> <span class="fu">makeResampleDesc</span>(<span class="at">method =</span> <span class="st">"CV"</span>, <span class="at">iters =</span> <span class="dv">10</span>, <span class="at">predict =</span> <span class="st">"both"</span>)</span>
<span id="cb126-4"><a href="#cb126-4" aria-hidden="true" tabindex="-1"></a>lrn <span class="ot">&lt;-</span> <span class="fu">makeLearner</span>(<span class="st">"classif.xgboost"</span>, <span class="at">nrounds =</span> <span class="dv">500</span>, <span class="at">max_depth =</span> <span class="dv">4</span>, <span class="at">eta =</span> <span class="fl">0.2254931</span>)</span>
<span id="cb126-5"><a href="#cb126-5" aria-hidden="true" tabindex="-1"></a>lc2 <span class="ot">&lt;-</span> <span class="fu">generateLearningCurveData</span>(</span>
<span id="cb126-6"><a href="#cb126-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">learners =</span> lrn,</span>
<span id="cb126-7"><a href="#cb126-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">task =</span> datos.task,</span>
<span id="cb126-8"><a href="#cb126-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">percs =</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>),</span>
<span id="cb126-9"><a href="#cb126-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">measures =</span> <span class="fu">list</span>(ber, <span class="fu">setAggregation</span>(ber, train.mean)),</span>
<span id="cb126-10"><a href="#cb126-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">resampling =</span> rin2,</span>
<span id="cb126-11"><a href="#cb126-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">show.info =</span> <span class="cn">FALSE</span></span>
<span id="cb126-12"><a href="#cb126-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb126-13"><a href="#cb126-13" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="fu">plotLearningCurve</span>(lc2, <span class="at">facet =</span> <span class="st">"learner"</span>)</span>
<span id="cb126-14"><a href="#cb126-14" aria-hidden="true" tabindex="-1"></a>p</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Proyecto_modelos_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Observando la grafica de aprendizaje se puede observar que el modelo no tiene overfitting ya que aunque las curvas no son iguales, estas convergen.</p>
</section>
<section id="predicciones-y-datos-de-validación" class="level4">
<h4 class="anchored" data-anchor-id="predicciones-y-datos-de-validación">4.3.3 Predicciones y datos de validación</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb127"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb127-1"><a href="#cb127-1" aria-hidden="true" tabindex="-1"></a>train1<span class="sc">$</span>TIPO <span class="ot">&lt;-</span> TIPO_temp</span>
<span id="cb127-2"><a href="#cb127-2" aria-hidden="true" tabindex="-1"></a>xgb_model <span class="ot">&lt;-</span> <span class="fu">xgboost</span>(<span class="at">data =</span> <span class="fu">as.matrix</span>(train1[, <span class="sc">-</span><span class="fu">which</span>(<span class="fu">colnames</span>(train1) <span class="sc">==</span> <span class="st">"TIPO"</span>)]), </span>
<span id="cb127-3"><a href="#cb127-3" aria-hidden="true" tabindex="-1"></a>                     <span class="at">label =</span> train1[, <span class="fu">c</span>(<span class="st">'TIPO'</span>)],</span>
<span id="cb127-4"><a href="#cb127-4" aria-hidden="true" tabindex="-1"></a>                     <span class="at">nrounds =</span> <span class="dv">500</span>, <span class="at">max_depth=</span><span class="dv">4</span>, <span class="at">eta=</span><span class="fl">0.2254931</span>, <span class="at">verbose=</span><span class="dv">0</span>)</span>
<span id="cb127-5"><a href="#cb127-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-6"><a href="#cb127-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Make predictions</span></span>
<span id="cb127-7"><a href="#cb127-7" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">predict</span>(xgb_model, <span class="fu">as.matrix</span>(test1[, <span class="sc">-</span><span class="fu">which</span>(<span class="fu">colnames</span>(test1) <span class="sc">==</span> <span class="st">"TIPO"</span>)]))</span>
<span id="cb127-8"><a href="#cb127-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb127-9"><a href="#cb127-9" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(predictions <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb127-10"><a href="#cb127-10" aria-hidden="true" tabindex="-1"></a>predictions <span class="ot">&lt;-</span> <span class="fu">factor</span>(predictions)</span>
<span id="cb127-11"><a href="#cb127-11" aria-hidden="true" tabindex="-1"></a><span class="co"># datos2 &lt;- as.data.frame(datos2)</span></span>
<span id="cb127-12"><a href="#cb127-12" aria-hidden="true" tabindex="-1"></a><span class="co"># datos2$TIPO &lt;- factor(datos2$TIPO, levels = c('0', '1'))</span></span>
<span id="cb127-13"><a href="#cb127-13" aria-hidden="true" tabindex="-1"></a><span class="co"># datos2$TIPO</span></span>
<span id="cb127-14"><a href="#cb127-14" aria-hidden="true" tabindex="-1"></a>confusion_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(<span class="at">reference =</span> <span class="fu">as.factor</span>(test1<span class="sc">$</span>TIPO), <span class="at">data =</span> predictions)</span>
<span id="cb127-15"><a href="#cb127-15" aria-hidden="true" tabindex="-1"></a>confusion_matrix</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction    0    1
         0 6871 1174
         1 1348 2758
                                          
               Accuracy : 0.7924          
                 95% CI : (0.7851, 0.7996)
    No Information Rate : 0.6764          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.5313          
                                          
 Mcnemar's Test P-Value : 0.0005713       
                                          
            Sensitivity : 0.8360          
            Specificity : 0.7014          
         Pos Pred Value : 0.8541          
         Neg Pred Value : 0.6717          
             Prevalence : 0.6764          
         Detection Rate : 0.5655          
   Detection Prevalence : 0.6621          
      Balanced Accuracy : 0.7687          
                                          
       'Positive' Class : 0               
                                          </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb129"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb129-1"><a href="#cb129-1" aria-hidden="true" tabindex="-1"></a>f1_score <span class="ot">&lt;-</span> confusion_matrix<span class="sc">$</span>byClass[<span class="st">"F1"</span>]</span>
<span id="cb129-2"><a href="#cb129-2" aria-hidden="true" tabindex="-1"></a>f1_score</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       F1 
0.8449336 </code></pre>
</div>
</div>
</section>
</section>
<section id="random-forest" class="level3">
<h3 class="anchored" data-anchor-id="random-forest">4.4 Random Forest</h3>
<section id="parameter-tuning-1" class="level4">
<h4 class="anchored" data-anchor-id="parameter-tuning-1">4.4.1 Parameter tuning</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb131"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb131-1"><a href="#cb131-1" aria-hidden="true" tabindex="-1"></a>classifier <span class="ot">&lt;-</span> <span class="fu">makeClassifTask</span>(</span>
<span id="cb131-2"><a href="#cb131-2" aria-hidden="true" tabindex="-1"></a>    <span class="at">data=</span>train, </span>
<span id="cb131-3"><a href="#cb131-3" aria-hidden="true" tabindex="-1"></a>    <span class="at">target=</span><span class="st">"TIPO"</span></span>
<span id="cb131-4"><a href="#cb131-4" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb131-5"><a href="#cb131-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-6"><a href="#cb131-6" aria-hidden="true" tabindex="-1"></a>param_grid <span class="ot">&lt;-</span> <span class="fu">makeParamSet</span>(<span class="fu">makeDiscreteParam</span>(<span class="st">"ntree"</span>,<span class="at">values=</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">500</span>, <span class="at">by =</span> <span class="dv">25</span>)))</span>
<span id="cb131-7"><a href="#cb131-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-8"><a href="#cb131-8" aria-hidden="true" tabindex="-1"></a>control_grid <span class="ot">&lt;-</span> <span class="fu">makeTuneControlGrid</span>()</span>
<span id="cb131-9"><a href="#cb131-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-10"><a href="#cb131-10" aria-hidden="true" tabindex="-1"></a>resample <span class="ot">&lt;-</span> <span class="fu">makeResampleDesc</span>(<span class="st">"CV"</span>, <span class="at">iters =</span> 3L)</span>
<span id="cb131-11"><a href="#cb131-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-12"><a href="#cb131-12" aria-hidden="true" tabindex="-1"></a>measure <span class="ot">&lt;-</span> acc</span>
<span id="cb131-13"><a href="#cb131-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb131-14"><a href="#cb131-14" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb131-15"><a href="#cb131-15" aria-hidden="true" tabindex="-1"></a>dt_tuneparam <span class="ot">&lt;-</span> <span class="fu">tuneParams</span>(<span class="at">learner=</span><span class="st">'classif.randomForest'</span>, </span>
<span id="cb131-16"><a href="#cb131-16" aria-hidden="true" tabindex="-1"></a> <span class="at">task=</span>classifier, </span>
<span id="cb131-17"><a href="#cb131-17" aria-hidden="true" tabindex="-1"></a> <span class="at">resampling =</span> resample,</span>
<span id="cb131-18"><a href="#cb131-18" aria-hidden="true" tabindex="-1"></a> <span class="at">measures =</span> measure,</span>
<span id="cb131-19"><a href="#cb131-19" aria-hidden="true" tabindex="-1"></a> <span class="at">par.set=</span>param_grid, </span>
<span id="cb131-20"><a href="#cb131-20" aria-hidden="true" tabindex="-1"></a> <span class="at">control=</span>control_grid, </span>
<span id="cb131-21"><a href="#cb131-21" aria-hidden="true" tabindex="-1"></a> <span class="at">show.info =</span> <span class="cn">TRUE</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune] Started tuning learner classif.randomForest for parameter set:</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>          Type len Def                                   Constr Req Tunable
ntree discrete   -   - 0,25,50,75,100,125,150,175,200,225,25...   -    TRUE
      Trafo
ntree     -</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>With control class: TuneControlGrid</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Imputation value: -0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] Setting hyperpars failed: Error in setHyperPars2.Learner(learner, insert(par.vals, args)) : 
  0 is not feasible for parameter 'ntree'!</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 1: ntree=0</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 1: acc.test.mean=      NA; time: 0.0 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 2: ntree=25</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 2: acc.test.mean=0.9492452; time: 0.0 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 3: ntree=50</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 3: acc.test.mean=0.9517142; time: 0.0 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 4: ntree=75</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 4: acc.test.mean=0.9518552; time: 0.0 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 5: ntree=100</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 5: acc.test.mean=0.9524901; time: 0.1 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 6: ntree=125</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 6: acc.test.mean=0.9521726; time: 0.1 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 7: ntree=150</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 7: acc.test.mean=0.9530897; time: 0.1 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 8: ntree=175</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 8: acc.test.mean=0.9527017; time: 0.1 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 9: ntree=200</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 9: acc.test.mean=0.9524901; time: 0.1 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 10: ntree=225</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 10: acc.test.mean=0.9532660; time: 0.1 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 11: ntree=250</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 11: acc.test.mean=0.9531250; time: 0.1 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 12: ntree=275</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 12: acc.test.mean=0.9528781; time: 0.1 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 13: ntree=300</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 13: acc.test.mean=0.9532308; time: 0.1 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 14: ntree=325</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 14: acc.test.mean=0.9527723; time: 0.2 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 15: ntree=350</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 15: acc.test.mean=0.9528428; time: 0.2 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 16: ntree=375</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 16: acc.test.mean=0.9527723; time: 0.2 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 17: ntree=400</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 17: acc.test.mean=0.9529134; time: 0.2 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 18: ntree=425</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 18: acc.test.mean=0.9528076; time: 0.2 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 19: ntree=450</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 19: acc.test.mean=0.9533366; time: 0.2 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 20: ntree=475</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 20: acc.test.mean=0.9530192; time: 0.2 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-x] 21: ntree=500</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune-y] 21: acc.test.mean=0.9533719; time: 0.2 min</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>[Tune] Result: ntree=500 : acc.test.mean=0.9533719</code></pre>
</div>
<div class="sourceCode cell-code" id="cb180"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb180-1"><a href="#cb180-1" aria-hidden="true" tabindex="-1"></a>result_hyperparam <span class="ot">&lt;-</span> <span class="fu">generateHyperParsEffectData</span>(dt_tuneparam, <span class="at">partial.dep =</span> <span class="cn">TRUE</span>)</span>
<span id="cb180-2"><a href="#cb180-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb180-3"><a href="#cb180-3" aria-hidden="true" tabindex="-1"></a>best_parameters <span class="ot">=</span> <span class="fu">setHyperPars</span>(</span>
<span id="cb180-4"><a href="#cb180-4" aria-hidden="true" tabindex="-1"></a>    <span class="fu">makeLearner</span>(<span class="st">"classif.randomForest"</span>), </span>
<span id="cb180-5"><a href="#cb180-5" aria-hidden="true" tabindex="-1"></a>    <span class="at">par.vals =</span> dt_tuneparam<span class="sc">$</span>x</span>
<span id="cb180-6"><a href="#cb180-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb180-7"><a href="#cb180-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb180-8"><a href="#cb180-8" aria-hidden="true" tabindex="-1"></a>best_model <span class="ot">=</span> <span class="fu">train</span>(best_parameters, classifier)</span>
<span id="cb180-9"><a href="#cb180-9" aria-hidden="true" tabindex="-1"></a>best_params <span class="ot">&lt;-</span> <span class="fu">getHyperPars</span>(best_model<span class="sc">$</span>learner)</span>
<span id="cb180-10"><a href="#cb180-10" aria-hidden="true" tabindex="-1"></a>best_params</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>$ntree
[1] 500</code></pre>
</div>
</div>
<p>Luego de realizar el tuneo de los parametros y ajustar los parametros de este modelo, se determinó que la mejor cantidad de árboles para nuestro conjunto de datos y objetivos específicos es 500. Esta elección se basó en un proceso de evaluación riguroso que consideró medidas de rendimiento y garantizó un equilibrio adecuado entre precisión y eficiencia computacional.</p>
</section>
<section id="curva-de-aprendizaje-2" class="level4">
<h4 class="anchored" data-anchor-id="curva-de-aprendizaje-2">4.4.2 Curva de aprendizaje</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb182"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb182-1"><a href="#cb182-1" aria-hidden="true" tabindex="-1"></a>datos.task <span class="ot">=</span> <span class="fu">makeClassifTask</span>(<span class="at">data =</span> train, <span class="at">target =</span> <span class="st">"TIPO"</span>)</span>
<span id="cb182-2"><a href="#cb182-2" aria-hidden="true" tabindex="-1"></a>rin2 <span class="ot">=</span> <span class="fu">makeResampleDesc</span>(<span class="at">method =</span> <span class="st">"CV"</span>, <span class="at">iters =</span> <span class="dv">10</span>, <span class="at">predict =</span> <span class="st">"both"</span>)</span>
<span id="cb182-3"><a href="#cb182-3" aria-hidden="true" tabindex="-1"></a>lrn <span class="ot">=</span> <span class="fu">makeLearner</span>(<span class="st">"classif.randomForest"</span>, <span class="at">ntree =</span> <span class="dv">500</span>)</span>
<span id="cb182-4"><a href="#cb182-4" aria-hidden="true" tabindex="-1"></a>lc2 <span class="ot">=</span> <span class="fu">generateLearningCurveData</span>(<span class="at">learners =</span> lrn, <span class="at">task =</span> datos.task,</span>
<span id="cb182-5"><a href="#cb182-5" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">percs =</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>),</span>
<span id="cb182-6"><a href="#cb182-6" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">measures =</span> <span class="fu">list</span>(ber, <span class="fu">setAggregation</span>(ber, train.mean)), <span class="at">resampling =</span> rin2,</span>
<span id="cb182-7"><a href="#cb182-7" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">show.info =</span> <span class="cn">FALSE</span>)</span>
<span id="cb182-8"><a href="#cb182-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plotLearningCurve</span>(lc2, <span class="at">facet =</span> <span class="st">"learner"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Proyecto_modelos_files/figure-html/unnamed-chunk-24-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Como se puede observar en la grafica que muestra la curva de aprendizaje el error de entrenamiento sigue disminuyendo a medida que se agregan más datos, pero el error de validación se estabiliza, sugiriendo asi que el modelo está memorizando los datos de entrenamiento y no generalizando bien a nuevos datos. Indicando así que el modelo presenta overfitting.</p>
</section>
<section id="predicciones-1" class="level4">
<h4 class="anchored" data-anchor-id="predicciones-1">4.4.3 Predicciones</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb183"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb183-1"><a href="#cb183-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb183-2"><a href="#cb183-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb183-3"><a href="#cb183-3" aria-hidden="true" tabindex="-1"></a>modelo_rf <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(TIPO <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">ntree =</span> <span class="dv">500</span>)</span>
<span id="cb183-4"><a href="#cb183-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb183-5"><a href="#cb183-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb183-6"><a href="#cb183-6" aria-hidden="true" tabindex="-1"></a>predicciones <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo_rf, test)</span>
<span id="cb183-7"><a href="#cb183-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb183-8"><a href="#cb183-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb183-9"><a href="#cb183-9" aria-hidden="true" tabindex="-1"></a>confusion_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(<span class="at">reference=</span>test<span class="sc">$</span>TIPO, <span class="at">data =</span> predicciones)</span>
<span id="cb183-10"><a href="#cb183-10" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(confusion_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction muerto vivo
    muerto   3809  447
    vivo      123 7772
                                          
               Accuracy : 0.9531          
                 95% CI : (0.9492, 0.9568)
    No Information Rate : 0.6764          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.8951          
                                          
 Mcnemar's Test P-Value : &lt; 2.2e-16       
                                          
            Sensitivity : 0.9687          
            Specificity : 0.9456          
         Pos Pred Value : 0.8950          
         Neg Pred Value : 0.9844          
             Prevalence : 0.3236          
         Detection Rate : 0.3135          
   Detection Prevalence : 0.3503          
      Balanced Accuracy : 0.9572          
                                          
       'Positive' Class : muerto          
                                          </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb185"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb185-1"><a href="#cb185-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb185-2"><a href="#cb185-2" aria-hidden="true" tabindex="-1"></a>porcentaje <span class="ot">&lt;-</span> <span class="fl">0.5</span></span>
<span id="cb185-3"><a href="#cb185-3" aria-hidden="true" tabindex="-1"></a>corte <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">nrow</span>(test), <span class="fu">nrow</span>(test) <span class="sc">*</span> porcentaje)</span>
<span id="cb185-4"><a href="#cb185-4" aria-hidden="true" tabindex="-1"></a>test2 <span class="ot">&lt;-</span> test[corte, ]</span>
<span id="cb185-5"><a href="#cb185-5" aria-hidden="true" tabindex="-1"></a>validation2 <span class="ot">&lt;-</span> test[<span class="sc">-</span>corte,]</span>
<span id="cb185-6"><a href="#cb185-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb185-7"><a href="#cb185-7" aria-hidden="true" tabindex="-1"></a>modelo_rf <span class="ot">&lt;-</span> <span class="fu">randomForest</span>(TIPO <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">ntree =</span> <span class="dv">500</span>)</span>
<span id="cb185-8"><a href="#cb185-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb185-9"><a href="#cb185-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb185-10"><a href="#cb185-10" aria-hidden="true" tabindex="-1"></a>predicciones <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo_rf, test2)</span>
<span id="cb185-11"><a href="#cb185-11" aria-hidden="true" tabindex="-1"></a>predicciones2 <span class="ot">&lt;-</span> <span class="fu">predict</span>(modelo_rf, validation2)</span>
<span id="cb185-12"><a href="#cb185-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb185-13"><a href="#cb185-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb185-14"><a href="#cb185-14" aria-hidden="true" tabindex="-1"></a>confusion_matrix <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(<span class="at">reference=</span>test2<span class="sc">$</span>TIPO, <span class="at">data =</span> predicciones)</span>
<span id="cb185-15"><a href="#cb185-15" aria-hidden="true" tabindex="-1"></a>confusion_matrix2 <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(<span class="at">reference=</span>validation2<span class="sc">$</span>TIPO, <span class="at">data =</span> predicciones2)</span>
<span id="cb185-16"><a href="#cb185-16" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(confusion_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction muerto vivo
    muerto   1925  220
    vivo       63 3867
                                          
               Accuracy : 0.9534          
                 95% CI : (0.9478, 0.9586)
    No Information Rate : 0.6728          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.8963          
                                          
 Mcnemar's Test P-Value : &lt; 2.2e-16       
                                          
            Sensitivity : 0.9683          
            Specificity : 0.9462          
         Pos Pred Value : 0.8974          
         Neg Pred Value : 0.9840          
             Prevalence : 0.3272          
         Detection Rate : 0.3169          
   Detection Prevalence : 0.3531          
      Balanced Accuracy : 0.9572          
                                          
       'Positive' Class : muerto          
                                          </code></pre>
</div>
<div class="sourceCode cell-code" id="cb187"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb187-1"><a href="#cb187-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(confusion_matrix)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction muerto vivo
    muerto   1925  220
    vivo       63 3867
                                          
               Accuracy : 0.9534          
                 95% CI : (0.9478, 0.9586)
    No Information Rate : 0.6728          
    P-Value [Acc &gt; NIR] : &lt; 2.2e-16       
                                          
                  Kappa : 0.8963          
                                          
 Mcnemar's Test P-Value : &lt; 2.2e-16       
                                          
            Sensitivity : 0.9683          
            Specificity : 0.9462          
         Pos Pred Value : 0.8974          
         Neg Pred Value : 0.9840          
             Prevalence : 0.3272          
         Detection Rate : 0.3169          
   Detection Prevalence : 0.3531          
      Balanced Accuracy : 0.9572          
                                          
       'Positive' Class : muerto          
                                          </code></pre>
</div>
</div>
<p>Al usar solo la data de test y luego usar una de validation, se pude observar una diferencia importante en el accuracy. Esto indica overfitting.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb189"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb189-1"><a href="#cb189-1" aria-hidden="true" tabindex="-1"></a>f1_score <span class="ot">&lt;-</span> confusion_matrix<span class="sc">$</span>byClass[<span class="st">"F1"</span>]</span>
<span id="cb189-2"><a href="#cb189-2" aria-hidden="true" tabindex="-1"></a>f1_score</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       F1 
0.9315267 </code></pre>
</div>
</div>
</section>
</section>
<section id="regresión-logística-regularizada" class="level3">
<h3 class="anchored" data-anchor-id="regresión-logística-regularizada">4.5 Regresión logística regularizada</h3>
<section id="parameter-tunning-1" class="level4">
<h4 class="anchored" data-anchor-id="parameter-tunning-1">4.5.1 Parameter tunning</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb191"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb191-1"><a href="#cb191-1" aria-hidden="true" tabindex="-1"></a>grid <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(<span class="at">alpha =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>), <span class="at">lambda =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>))</span>
<span id="cb191-2"><a href="#cb191-2" aria-hidden="true" tabindex="-1"></a>ctrl <span class="ot">&lt;-</span> <span class="fu">trainControl</span>(<span class="at">method =</span> <span class="st">"cv"</span>, <span class="at">number =</span> <span class="dv">10</span>)</span>
<span id="cb191-3"><a href="#cb191-3" aria-hidden="true" tabindex="-1"></a>model <span class="ot">&lt;-</span> caret<span class="sc">::</span><span class="fu">train</span>(TIPO <span class="sc">~</span> ., <span class="at">data =</span> train, <span class="at">method =</span> <span class="st">"glmnet"</span>, <span class="at">tuneGrid =</span> grid, <span class="at">trControl =</span> ctrl)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: from glmnet C++ code (error code -66); Convergence for 66th lambda
value not reached after maxit=100000 iterations; solutions for larger lambdas
returned</code></pre>
</div>
<div class="sourceCode cell-code" id="cb193"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb193-1"><a href="#cb193-1" aria-hidden="true" tabindex="-1"></a>best_alpha <span class="ot">&lt;-</span> model<span class="sc">$</span>bestTune<span class="sc">$</span>alpha</span>
<span id="cb193-2"><a href="#cb193-2" aria-hidden="true" tabindex="-1"></a>best_lambda <span class="ot">&lt;-</span> model<span class="sc">$</span>bestTune<span class="sc">$</span>lambda</span>
<span id="cb193-3"><a href="#cb193-3" aria-hidden="true" tabindex="-1"></a>best_alpha</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb195"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb195-1"><a href="#cb195-1" aria-hidden="true" tabindex="-1"></a>best_lambda</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 0.1</code></pre>
</div>
</div>
<p>Luego de realizar el tuneo de parámetros se obtuvo que los mejores parámetros son un alpha de 1 y un lambda de 0.1.</p>
</section>
<section id="curva-de-aprendizaje-3" class="level4">
<h4 class="anchored" data-anchor-id="curva-de-aprendizaje-3">4.5.2 Curva de aprendizaje</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb197"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb197-1"><a href="#cb197-1" aria-hidden="true" tabindex="-1"></a>datos.task <span class="ot">=</span> <span class="fu">makeClassifTask</span>(<span class="at">data =</span> train, <span class="at">target =</span> <span class="st">"TIPO"</span>)</span>
<span id="cb197-2"><a href="#cb197-2" aria-hidden="true" tabindex="-1"></a>rin2 <span class="ot">=</span> <span class="fu">makeResampleDesc</span>(<span class="at">method =</span> <span class="st">"CV"</span>, <span class="at">iters =</span> <span class="dv">10</span>, <span class="at">predict =</span> <span class="st">"both"</span>)</span>
<span id="cb197-3"><a href="#cb197-3" aria-hidden="true" tabindex="-1"></a>lrn <span class="ot">=</span> <span class="fu">makeLearner</span>(<span class="st">"classif.glmnet"</span>, <span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">lambda =</span> <span class="fl">0.1</span>)</span>
<span id="cb197-4"><a href="#cb197-4" aria-hidden="true" tabindex="-1"></a>lc2 <span class="ot">=</span> <span class="fu">generateLearningCurveData</span>(<span class="at">learners =</span> lrn, <span class="at">task =</span> datos.task,</span>
<span id="cb197-5"><a href="#cb197-5" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">percs =</span> <span class="fu">seq</span>(<span class="fl">0.1</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>),</span>
<span id="cb197-6"><a href="#cb197-6" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">measures =</span> <span class="fu">list</span>(ber, <span class="fu">setAggregation</span>(ber, train.mean)), <span class="at">resampling =</span> rin2,</span>
<span id="cb197-7"><a href="#cb197-7" aria-hidden="true" tabindex="-1"></a>                                    <span class="at">show.info =</span> <span class="cn">FALSE</span>)</span>
<span id="cb197-8"><a href="#cb197-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plotLearningCurve</span>(lc2, <span class="at">facet =</span> <span class="st">"learner"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<p><img src="Proyecto_modelos_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid" width="672"></p>
</div>
</div>
<p>Es posible observar, de la curva de aprendizaje, que a pesar de que las curvas están muy similares, el valor del accuracy con el 100% de los datos baja demasiado. Es posible que se tenga underfitting.</p>
</section>
<section id="predicciones-2" class="level4">
<h4 class="anchored" data-anchor-id="predicciones-2">4.5.3 Predicciones</h4>
<div class="cell">
<div class="sourceCode cell-code" id="cb198"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb198-1"><a href="#cb198-1" aria-hidden="true" tabindex="-1"></a>X_train <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">select</span>(train1, <span class="sc">-</span>TIPO))</span>
<span id="cb198-2"><a href="#cb198-2" aria-hidden="true" tabindex="-1"></a>y_train <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(train1<span class="sc">$</span>TIPO)</span>
<span id="cb198-3"><a href="#cb198-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb198-4"><a href="#cb198-4" aria-hidden="true" tabindex="-1"></a>X_test <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(<span class="fu">select</span>(test1, <span class="sc">-</span>TIPO))</span>
<span id="cb198-5"><a href="#cb198-5" aria-hidden="true" tabindex="-1"></a>y_test <span class="ot">&lt;-</span> <span class="fu">as.matrix</span>(test1<span class="sc">$</span>TIPO)</span>
<span id="cb198-6"><a href="#cb198-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb198-7"><a href="#cb198-7" aria-hidden="true" tabindex="-1"></a>ridge_model <span class="ot">&lt;-</span> <span class="fu">glmnet</span>(X_train, y_train, <span class="at">family =</span> <span class="st">"binomial"</span>, <span class="at">alpha =</span> <span class="dv">1</span>, <span class="at">lambda =</span> <span class="fl">0.1</span>)</span>
<span id="cb198-8"><a href="#cb198-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb198-9"><a href="#cb198-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Realizar predicciones en los datos de prueba</span></span>
<span id="cb198-10"><a href="#cb198-10" aria-hidden="true" tabindex="-1"></a>y_pred <span class="ot">&lt;-</span> <span class="fu">predict</span>(ridge_model, <span class="at">newx =</span> X_test, <span class="at">s =</span> <span class="st">"lambda.min"</span>, <span class="at">type =</span> <span class="st">"response"</span>)</span>
<span id="cb198-11"><a href="#cb198-11" aria-hidden="true" tabindex="-1"></a>y_pred <span class="ot">&lt;-</span> <span class="fu">ifelse</span>(y_pred <span class="sc">&gt;</span> <span class="fl">0.5</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb198-12"><a href="#cb198-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb198-13"><a href="#cb198-13" aria-hidden="true" tabindex="-1"></a>cf <span class="ot">&lt;-</span> <span class="fu">confusionMatrix</span>(<span class="at">reference =</span> <span class="fu">as.factor</span>(test1<span class="sc">$</span>TIPO), <span class="at">data =</span> <span class="fu">as.factor</span>(y_pred))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in confusionMatrix.default(reference = as.factor(test1$TIPO), data =
as.factor(y_pred)): Levels are not in the same order for reference and data.
Refactoring data to match.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb200"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb200-1"><a href="#cb200-1" aria-hidden="true" tabindex="-1"></a>cf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Confusion Matrix and Statistics

          Reference
Prediction    0    1
         0 8219 3932
         1    0    0
                                         
               Accuracy : 0.6764         
                 95% CI : (0.668, 0.6847)
    No Information Rate : 0.6764         
    P-Value [Acc &gt; NIR] : 0.5043         
                                         
                  Kappa : 0              
                                         
 Mcnemar's Test P-Value : &lt;2e-16         
                                         
            Sensitivity : 1.0000         
            Specificity : 0.0000         
         Pos Pred Value : 0.6764         
         Neg Pred Value :    NaN         
             Prevalence : 0.6764         
         Detection Rate : 0.6764         
   Detection Prevalence : 1.0000         
      Balanced Accuracy : 0.5000         
                                         
       'Positive' Class : 0              
                                         </code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb202"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb202-1"><a href="#cb202-1" aria-hidden="true" tabindex="-1"></a>f1_score <span class="ot">&lt;-</span> cf<span class="sc">$</span>byClass[<span class="st">"F1"</span>]</span>
<span id="cb202-2"><a href="#cb202-2" aria-hidden="true" tabindex="-1"></a>f1_score</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      F1 
0.806971 </code></pre>
</div>
</div>
</section>
</section>
</section>
<section id="discusión-de-resultados" class="level2">
<h2 class="anchored" data-anchor-id="discusión-de-resultados">5. Discusión de resultados</h2>
<p>Tras haber realizado las predicciones con cada modelo obtuvimos los siguientes resultados:</p>
<section id="svm-1" class="level3">
<h3 class="anchored" data-anchor-id="svm-1">SVM</h3>
<ul>
<li>Accuracy: 0.9393</li>
<li>Sensitivity: 1</li>
<li>Specificity: 0.9103</li>
<li>F1: 0.9143</li>
</ul>
</section>
<section id="red-neuronal-1" class="level3">
<h3 class="anchored" data-anchor-id="red-neuronal-1">Red Neuronal</h3>
<ul>
<li>Accuracy: 0.9391</li>
<li>Sensitivity: 0.9894</li>
<li>Specificity: 0.9148</li>
<li>F1: 0.9137</li>
</ul>
</section>
<section id="xgboost-1" class="level3">
<h3 class="anchored" data-anchor-id="xgboost-1">XGBoost</h3>
<ul>
<li>Accuracy: 0.7924</li>
<li>Sensitivity: 0.836</li>
<li>Specificity: 0.7014</li>
<li>F1: 0.8449</li>
</ul>
</section>
<section id="random-forest-1" class="level3">
<h3 class="anchored" data-anchor-id="random-forest-1">Random Forest</h3>
<ul>
<li>Accuracy: 0.9531</li>
<li>Sensitivity: 0.9687</li>
<li>Specificity: 0.9456</li>
<li>F1: 0.9303</li>
</ul>
</section>
<section id="regresión-logística-regularizada-1" class="level3">
<h3 class="anchored" data-anchor-id="regresión-logística-regularizada-1">Regresión logística regularizada</h3>
<ul>
<li>Accuracy: 0.67</li>
<li>Sensitivity: 1</li>
<li>Specificity: 0</li>
<li>F1: 0.80697</li>
</ul>
<p>Cabe mencionar que de los modelos anteriores los únicos que no estan ni sobre ajustados ni infra ajustado son: <strong>La red neuronal y XGBoost</strong></p>
<p>Sobre la precisión de los diferentes modelos para poder predecir si el embarazo terminará siendo un aborto o si el embarazo se dara con normalidad, tenemos que el peor modelo fue la regresion logistica con un 0.67 de accuracy esto se pudo dar ya que este es un algoritmo de clasificación binaria por lo que la mejor metrica para evaluarlo no sería por medio del accuracy. Mientras que el mejor modelo fue el random forest con 0.95 de accuracy pero este es uno de los modelos que se encuentra sobre ajustado por lo que realmente no es un buen resultado para nuestra investigación, por la misma razón el modelo hace las predicciones con los patrones del dataset en especifico. Por otro lado de los modelos que <strong>NO</strong> se encuentran sobre ajustados tenemos que la red neuronal obtuvo un 0.93 de accuracy el cual fue superior al 0.79 de accuracy del XGBoost, por lo que el modelo que tuvo una precisión más alta y es significativo para la investigacion es <strong>La red neuronal</strong>.</p>
<p>Observando la capacidad de los modelos para predecir los verdaderos positivos (True Positive), se puede observar que el modelo que mejor predice los verdaderos positivos es la SVM y la regresion Logistica Regularizada, ambas con un valor de 1. Para la Regresion Logistica esto se puede deber a que su humbral este ajustado a los datos del data set y este marcando a todos los datos de una forma, agregado a desvalanceo que existe en los datos podria ser la razon del sobreajuste de este. Por otro lado tenemos tenemos que el XGBoost, con un valor de 0.836, esto se pudo dar ya que el modelo no logro capturar los patrones esenciales para casos positivos, o que el umbral utilizado para la clasificacion haya sido demasiado alto, lo que resulto en una menor tasa de verdaderos positivos. Por ultimo tenemos que el modelo que mejor pudo predecir los verdaderos positivos</p>
<p>Al observar la identificación de los verdaderos negativos (specificity) de los modelos, se puede evidenciar que el que mejor desempeño tuvo fue el random forest con 0.9456. El peor modelo para identificar verdaderos negativos fue la regresión logística regularizada, con 0. Esto último se puede deber al umbral utilizado para identificar una clase de la otra, de forma que la mayoría de datos tenían una probabilidad superior. Otro factor que afecta es el ligero desbalance mencionado previamente en los datos. Por otra parte, el random forest pudo tener un muy buen desempeño gracias a su manejo de características irrelevantes del dataset. Además, su mismo overfitting hizo que entendiera las reglas importantes del dataset que le permitieran identificar los verdaderos falsos.</p>
<p>Finalmente, la regresión logística tuvo el F1 más bajo y el random forest el más alto. Los atributos del random forest para el manejo de clases sin balance y su capacidad de aprender patrones complejos por su conjunto de árboles, permitieron que se desempeñara bastante bien en esta métrica. Por otra parte, la regresión logística puede que haya sido demasiado simple para la clasificación. Sin embargo, es importante notar que su F1 no es tan distinto a los demás modelos, a diferencia de su accuracy. Esto porque el desbalance de los datos causa que su accuracy no sea tan significativo. En general, por esta métrica la regresión no es un modelo tan malo, a pesar de su underfitting.</p>
<p>Tras haber hecho el análisis de cada uno de las métricas y tomando en cuenta únicamente los modelos que si proveen un aporte significativo a la investigación, el mejor modelo fue <strong>La Red Neuronal</strong>.</p>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->



</body></html>